fix(parser): raise ValidationError when SNS->SQS keys are missing
awslabs/aws-lambda-powertools-python pull request #1299
Opened 2022-07-14 10:56 UTC by rubenfonseca

**Issue number:** #1228

## Summary

### Changes

When UnsubscribeURL or SigningCertURL were missing from the SNS -> SQS payload, KeyError was thrown.
Since the objective of the parser is to validate the payload, we changed the code so it returns
an expected [ValidationError](https://prompt-build--pydantic-docs.netlify.app/#error-handling) instead.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of my this change
* [x] Changes are tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-07-14 13:07 UTC, heitorlessa requested changes
Looks great, a minor suggestion to make the tests more explicit. Super excited to see your first PR ;-)

2022-07-14 13:07 UTC, heitorlessa commented on tests/functional/parser/test_sns.py
> +        handle_sns_sqs_json_body(event_dict, LambdaContext())
```suggestion
def test_handle_sns_sqs_trigger_event_json_body_missing_signing_cert_url():
    # GIVEN an event is tampered with a missing SigningCertURL
    event_dict = load_event("snsSqsEvent.json")
    payload = json.loads(event_dict["Records"][0]["body"])
    payload.pop("SigningCertURL")
    event_dict["Records"][0]["body"] = json.dumps(payload)

    # WHEN parsing the payload
    # THEN raise a ValidationError error
    with pytest.raises(ValidationError):
        handle_sns_sqs_json_body(event_dict, LambdaContext())
```

Added an explicit description on GIVEN that this is tampered, not the behaviour we'd expect from SNS. Also removed the `assert` as it'll only test whether we're changing the underlying fake event.

2022-07-14 13:07 UTC, heitorlessa commented on tests/functional/parser/test_sns.py
> +        handle_sns_sqs_json_body(event_dict, LambdaContext())
```suggestion
def test_handle_sns_sqs_trigger_event_json_body_missing_unsubscribe_url():
    # GIVEN an event is tampered with a missing UnsubscribeURL
    event_dict = load_event("snsSqsEvent.json")
    payload = json.loads(event_dict["Records"][0]["body"])
    payload.pop("UnsubscribeURL")
    event_dict["Records"][0]["body"] = json.dumps(payload)

    # WHEN parsing the payload
    # THEN raise a ValidationError error
    with pytest.raises(ValidationError):
        handle_sns_sqs_json_body(event_dict, LambdaContext())
```

Same as earlier

2022-07-14 13:40 UTC, rubenfonseca commented
@heitorlessa thank you for the feedback, it makes 100% sense! 😎

2022-07-14 14:02 UTC, leandrodamascena commented on tests/functional/parser/test_sns.py
> +        handle_sns_sqs_json_body(event_dict, LambdaContext())
@heitorlessa this is an interesting approach. Technically I think that Assert makes sense but the reason you ask to remove it is to make the code cleaner and without deviation from what should really be tested. We are informing the payload statically (snsSqsEvent.json) and we are not previously changing it. So, in this case we are sure that the command (payload.pop) will work.

Good catch and new thing learned! Btw, I would have done exactly like you @rubenfonseca lol.

Congrats for your first PR @rubenfonseca :rocket: :+1:

2022-07-18 06:57 UTC, heitorlessa approved these changes

2022-07-18 06:57 UTC, heitorlessa commented
Thanks a lot @rubenfonseca ;)

2022-07-18 06:58 UTC, merged