chore(ci): automatically add area label based on title
awslabs/aws-lambda-powertools-python pull request #1300
Opened 2022-07-14 13:34 UTC by rubenfonseca

**Issue number:** #1009

## Summary

### Changes

Automatically add the respective `area` label for known areas. The area is derived from the PR title.

### User experience

When a contributor submits a PR, an `area/xxx` label should be automatically applied if the title mentions a known powertools area.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of my this change
* [ ] Changes are tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-07-14 13:40 UTC, heitorlessa commented on .github/scripts/label_pr_based_on_title.js
> +        "metric",
```suggestion
        "metrics",
```

2022-07-14 13:42 UTC, rubenfonseca commented
@heitorlessa I don't feel confortable having an array of areas in the JS files. Is there a central place anywhere in the repository where we have the canonical list of areas that we could reference instead?

2022-07-14 13:43 UTC, heitorlessa requested changes
another papercut crossed from the list o// Thank you!! Tiny typo on `metric` vs `metrics` only

2022-07-14 13:45 UTC, heitorlessa commented
> 

Closest we've got now is our new constants.js: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/scripts/constants.js

One of the work we should do is to standardize a baseline of labels (90% there) across all Powertools, then make sure they not only stay in sync but is also available across repos to fetch and use in any automation. We don't have that yet.

2022-07-15 08:14 UTC, rubenfonseca commented
I've pulled the known areas into a constant on `constants.js`

2022-07-15 09:27 UTC, heitorlessa approved these changes

2022-07-15 09:28 UTC, merged