feat(event_sources,event_handlers): Add support for Lambda Function URLs
awslabs/aws-lambda-powertools-python pull request #1408
Opened 2022-08-03 12:03 UTC by rubenfonseca

- feat(event_sources): add support for Lambda Function URL events
- feat(event_handlers): add support for Lambda Function URL
- chore(docs): add documentation for Lambda Functoin URLs

**Issue number:** #1142

## Summary

### Changes

> Please provide a summary of what's being changed

This PR adds support for Lambda Function URL events (data class) and event handlers.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-08-03 15:30 UTC, gwlester commented
Looks good -- thanks much!!!!

2022-08-03 16:02 UTC, jplock commented on aws_lambda_powertools/event_handler/lambda_function_url.py
> +    from aws_lambda_powertools.event_handler import LambdaFunctoinUrlResolver
spelling: `LambdaFunctoinUrlResolver` -> `LambdaFunctionUrlResolver`

2022-08-03 16:02 UTC, jplock commented on aws_lambda_powertools/event_handler/lambda_function_url.py
> +    app = LambdaFunctoinUrlResolver()
spelling: `LambdaFunctoinUrlResolver` -> `LambdaFunctionUrlResolver`

2022-08-03 16:04 UTC, jplock reviewed
Please correct spelling errors

2022-08-04 10:06 UTC, heitorlessa requested changes
looks great, thank you @rubenfonseca !!!! Minor suggestions that you can easily commit, then we're good to merge and release tomorrow!

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/event_handler/api_gateway.py
> +        if self._proxy_type == ProxyEventType.LambdaFunctionUrlEvent:
note to future self: we should improve the return type to a more accurate one with `@overload`.

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/event_handler/lambda_function_url.py
> +    For now, this seems to work the same way as API Gateway HTTP APIs Payload Format Version 2.0.
```suggestion
    Lambda Function URL follows the API Gateway HTTP APIs Payload Format Version 2.0.
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/event_handler/lambda_function_url.py
> +    Simple example with a custom lambda handler using the Tracer capture_lambda_handler decorator
```suggestion
    Simple example integrating with Tracer
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/logging/correlation_paths.py
> +LAMBDA_FUNCTION_URL = "requestContext.requestId"
```suggestion
LAMBDA_FUNCTION_URL = API_GATEWAY_REST
```

As they follow the same payload specification

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/event_handler/lambda_function_url.py
> +        return {"message": post_data["value"]}
```suggestion
        return {"message": post_data}
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +        cognito_identity = self["cognitoIdentity"] or {}
```suggestion
        cognito_identity = self["cognitoIdentity"] or {}  # not available in FunctionURL
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +        cognito_identity = self.get("cognitoIdentity") or {}
```suggestion
        cognito_identity = self.get("cognitoIdentity") or {}  # not available in FunctionURL
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +        cognito_identity = self.get("cognitoIdentity") or {}
```suggestion
        cognito_identity = self.get("cognitoIdentity") or {}  # not available in FunctionURL
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +        jwt = self.get("jwt") or {}
```suggestion
        jwt = self.get("jwt") or {}  # not available in FunctionURL
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +        jwt = self.get("jwt") or {}
```suggestion
        jwt = self.get("jwt") or {}  # not available in FunctionURL
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/common.py
> +        authentication = self["requestContext"].get("authentication") or {}
```suggestion
        # FunctionURL might have NONE as AuthZ
        authentication = self["requestContext"].get("authentication") or {}
```

2022-08-04 10:06 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/lambda_function_url_event.py
> +    These keys will have default values that come on the payload, but they are not useful since they can't be changed.
```suggestion
    Lambda Function URL follows the API Gateway HTTP APIs Payload Format Version 2.0.
    
    Keys related to API Gateway features not available in Function URL use a sentinel value (e.g.`routeKey`, `stage`).
```

Tip: Write first, edit to be more assertive (is or isnt?), and then settle for the shortest with the same meaning.

2022-08-04 10:06 UTC, heitorlessa commented on docs/core/event_handler/api_gateway.md
> +When using an [AWS Lambda Function URL](https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html), you can use `LambdaFunctionUrlResolver`.
```suggestion
When using [AWS Lambda Function URL](https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html), you can use `LambdaFunctionUrlResolver`.
```

2022-08-04 10:06 UTC, heitorlessa commented on docs/core/event_handler/api_gateway.md
> +Pre-flight (OPTIONS) calls are typically handled at the API Gateway or Lambda Function URL level as per [our sample infrastructure](#required-resources), no Lambda integration necessary. However, ALB
```suggestion
Pre-flight (OPTIONS) calls are typically handled at the API Gateway or Lambda Function URL level as per [our sample infrastructure](#required-resources), no Lambda integration is necessary. However, ALB expects you to handle pre-flight requests.
```

Fixing a old typo :D

2022-08-04 10:06 UTC, heitorlessa commented on docs/core/event_handler/api_gateway.md
```suggestion
???+ warning
    This feature requires API Gateway to configure binary media types, see [our sample infrastructure](#required-resources) for reference.

???+ note
    Lambda Function URLs handle binary media types automatically.
```

In this case, it's best so separate what's a warning vs a note - "Do something vs Business as usual"

2022-08-04 10:06 UTC, heitorlessa commented on docs/core/event_handler/api_gateway.md
> +You can instruct an event handler to use a custom serializer to best suit your needs, for example take into account Enums when serializing.
```suggestion
You can instruct event handler to use a custom serializer to best suit your needs, for example take into account Enums when serializing.
```

Great catch!!!!

2022-08-04 10:06 UTC, heitorlessa commented on docs/core/event_handler/api_gateway.md
> +* **Upfront investment**. You need custom build tooling to bundle assets, including [C bindings for runtime compatibility](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html){target="_
great catch!!

2022-08-04 10:06 UTC, heitorlessa commented on docs/index.md
> +| [Event handler: API Gateway, ALB and Lambda Function URL](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/) | Amazon API Gateway REST/HTTP API and ALB e
```suggestion
| [Event handler: API Gateway, ALB and Lambda Function URL](https://awslabs.github.io/aws-lambda-powertools-python/latest/core/event_handler/api_gateway/) | Amazon API Gateway REST/HTTP API and ALB event handler for Lambda functions invoked using Proxy integration, and Lambda Function URL                                               |
```

2022-08-04 10:06 UTC, heitorlessa commented on examples/event_handler_lambda_function_url/sam/template.yaml
> +        # Notice that values here are Lists of Strings, vs comma-separated values on API Gateway
Great note!

2022-08-04 10:06 UTC, heitorlessa commented on examples/event_handler_lambda_function_url/sam/template.yaml
> +        AuthType: NONE
```suggestion
        AuthType: NONE  # AWS_IAM for added security beyond sample documentation
```

2022-08-04 10:13 UTC, rubenfonseca commented on aws_lambda_powertools/event_handler/api_gateway.py
> +        if self._proxy_type == ProxyEventType.LambdaFunctionUrlEvent:
note to future self: wait for python 3.10 to actually have [proper pattern matching](https://peps.python.org/pep-0634/)

2022-08-04 10:16 UTC, heitorlessa commented
YES except we won’t be able to use it (unless someone backported it? :/

On Thu, 4 Aug 2022 at 12:13, Ruben Fonseca ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In aws_lambda_powertools/event_handler/api_gateway.py
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/1408#discussion_r937608757>
> :
>
> > @@ -546,6 +552,9 @@ def _to_proxy_event(self, event: Dict) -> BaseProxyEvent:
>          if self._proxy_type == ProxyEventType.APIGatewayProxyEventV2:
>              logger.debug("Converting event to API Gateway HTTP API contract")
>              return APIGatewayProxyEventV2(event)
> +        if self._proxy_type == ProxyEventType.LambdaFunctionUrlEvent:
>
> note to future self: wait for python 3.10 to actually have proper pattern
> matching <https://peps.python.org/pep-0634/>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/1408#discussion_r937608757>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBDYSRNV2NIQ6OXQAY3VXOJWDANCNFSM55OS2IVQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***
> com>
>

2022-08-04 12:05 UTC, heitorlessa approved these changes

2022-08-04 12:06 UTC, heitorlessa commented
Merging! Should be out in our next release tomorrow

2022-08-04 12:07 UTC, merged