docs(typing): snippets split, improved, and lint
awslabs/aws-lambda-powertools-python pull request #1465
Opened 2022-08-21 18:52 UTC by leandrodamascena

**Issue number:** #1453 

## Summary

### Changes

Changes snippet fictitious names to real code snippet filenames for easier discovery and collaboration to improve/correct document snippets.

Some examples have also been refactored so that the codes are complete and there are no lint/pre-commit hooks issues.

### User experience

Before:
![image](https://user-images.githubusercontent.com/4295173/185806475-21332ce1-23fa-481f-8985-2cc963e1e51c.png)

After:
![image](https://user-images.githubusercontent.com/4295173/185806495-e40bbd1b-3039-4b49-a745-22a312737f0f.png)
![image](https://user-images.githubusercontent.com/4295173/185806508-dc017203-2cb1-48ac-9242-0439d806ac15.png)

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-08-22 10:50 UTC, rubenfonseca requested changes
Some small things, just suggestions, feel free to re-write :)

2022-08-22 10:50 UTC, rubenfonseca commented on docs/utilities/typing.md
> +* Ease the development by providing the IDE type hint
```suggestion
* Ease the development by leveraging your IDE's type hints
```

2022-08-22 10:50 UTC, rubenfonseca commented on docs/utilities/typing.md
> +Using `LambdaContext` typing it is possible to access information and hints of all properties and methods implemented by Lambda context object.
```suggestion
Using `LambdaContext` typing makes it possible to access information and hints of all properties and methods implemented by Lambda context object.
```

2022-08-22 11:07 UTC, leandrodamascena commented on docs/utilities/typing.md
> +* Ease the development by providing the IDE type hint
Yup, this is better than my text!

2022-08-24 11:47 UTC, rubenfonseca approved these changes
Just a small thing that you can approve and LGTM

2022-08-24 11:47 UTC, rubenfonseca commented on docs/utilities/typing.md
> +Using `LambdaContext` typing make it possible to access information and hints of all properties and methods implemented by Lambda context object.
```suggestion
Using `LambdaContext` typing makes it possible to access information and hints of all properties and methods implemented by Lambda context object.
```

2022-08-25 08:11 UTC, heitorlessa commented on examples/typing/src/working_with_context_function.py
> +        ...
```suggestion
        ...
```

2022-08-25 08:12 UTC, merged