feat(event_handler): add cookies as 1st class citizen
awslabs/aws-lambda-powertools-python pull request #1487
Opened 2022-08-31 08:20 UTC by rubenfonseca

**Issue number:** #1192

## Summary

This PR adds first class support for Cookies.

_bigger description comming soon_

### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-08-31 18:27 UTC, rubenfonseca commented
@heitorlessa @leandrodamascena would appreciate early feedback on this one before I continue to apply changes

2022-08-31 18:27 UTC, rubenfonseca commented on aws_lambda_powertools/event_handler/api_gateway.py
> +        self.response.headers["Content-Encoding"].append("gzip")
Please ignore this line

2022-09-01 12:51 UTC, heitorlessa requested changes
super clean, I loved it. Some suggestions and two questions on why not enabling `httpOnly` and `Secure` attrs by default (there's probably good reasons that I prolly don't know)

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +        domain: Optional[str] = None,
```suggestion
        path: str = "",
        domain: str = "",
```

Setting as an empty string will simplify your conditional branch (`if path and len(path) > 0`) to `if path`.

`path: Optional[str] = None` is useful in scenarios when an empty string is valid too - `if path is not None` would accept a `""`.

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +        secure: Optional[bool] = None,
what problems do we cause by having it `True` by default?

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +        http_only: Optional[bool] = None,
what problems do we cause by having it `True` by default?

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +                payload.write("; MaxAge=0")
```suggestion
            if self.max_age >= 0:
                payload.write(f"; MaxAge={self.max_age}")
            else:
                payload.write("; MaxAge=0")
```

it could be me after fighting with CDK non-sense, but reading the initial logic meant that `Cookie(MaxAge=0)` wasn't possible.

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/headers_serializer.py
> +        return {"headers": combined_headers, "cookies": list(map(str, cookies))}
neat FP!

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +        payload = StringIO()
great to see the efficient use of memory ;)

2022-09-01 12:51 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +    def __str__(self) -> str:
For the length of string this is fine, but careful with `str` as it's one the slowest part in Python as it's actually a Class, and every call to `str()` creates an object + permutations.

I ran a quick benchmark and this part of the code is ~6ns so it's more than fine.

2022-09-01 12:51 UTC, heitorlessa commented on tests/e2e/event_handler/test_header_serializer.py
could you add a note here on the assertion?  it has quite a bit of logic we will forget when returning at some point.

2022-09-01 14:34 UTC, rubenfonseca commented on aws_lambda_powertools/shared/cookies.py
> +        secure: Optional[bool] = None,
> When a cookie has the Secure attribute, the user agent will include the cookie in an HTTP request only if the request is transmitted over a secure channel (typically HTTPS).

So I'm inclined to have it ON by default. The problem would manifest if hitting the Lambda from a browser via a HTTP endpoint: the browser will ignore the cookie.

2022-09-01 14:35 UTC, rubenfonseca commented on aws_lambda_powertools/shared/cookies.py
> +        http_only: Optional[bool] = None,
> The HttpOnly attribute restricts the cookie from being accessed by, for instance, [JavaScript](https://en.wikipedia.org/wiki/JavaScript),

I would be more worried to turn this on by default... I'll leave it as optional for now

2022-09-02 14:41 UTC, heitorlessa commented on aws_lambda_powertools/shared/cookies.py
> +    return timestamp.strftime("%a, %d %b %Y %H:%M:%S GMT")
```suggestion
def _format_date(timestamp: datetime) -> str:
    # Specification example: Wed, 21 Oct 2015 07:28:00 GMT
    return timestamp.strftime("%a, %d %b %Y %H:%M:%S GMT")
```

2022-09-02 14:48 UTC, heitorlessa commented on examples/event_handler_rest/src/fine_grained_responses.py
> +        cookies=[Cookie(name="session_id", value="12345", secure=True)],
```suggestion
        cookies=[Cookie(name="session_id", value="12345")],
```

2022-09-02 14:52 UTC, heitorlessa commented on tests/e2e/event_handler/test_header_serializer.py
> +        returned_value = ", ".join(sorted(response.headers[key].split(", ")))
Note for us: maybe we should have an utility function for this as we'll forget at some point (syntax et al)

2022-09-02 14:53 UTC, heitorlessa approved these changes

2022-09-02 15:21 UTC, merged