Feature request: Kinesis Data Firehose event envelope and parser model
awslabs/aws-lambda-powertools-python pull request #1556
Opened 2022-09-29 16:26 UTC by ran-isenberg

**Issue number:** 1555

## Summary
Add Kinesis Data Firehose event envelope and parser model

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-09-29 16:27 UTC, ran-isenberg commented on aws_lambda_powertools/shared/functions.py
> +        logger.debug("Decoding base64 record item before parsing")
removed the kafka from the shared function

2022-09-29 16:27 UTC, ran-isenberg commented on aws_lambda_powertools/utilities/parser/envelopes/kinesis.py
> +    all items in the list will be parsed as str and not as JSON (and vice versa)
typo :)

2022-09-29 16:28 UTC, ran-isenberg commented on aws_lambda_powertools/utilities/parser/models/kinesis.py
> +        return base64_decode(value)
old kinesis improvement

2022-10-03 13:08 UTC, heitorlessa commented
@leandrodamascena we might want to do an E2E for this. Due to parser's nature, it has the highest risk of causing runtime disruption.

2022-10-03 19:29 UTC, leandrodamascena commented
Hii @ran-isenberg thanks for one more PR :smiley:.. I'm starting to work on it now.

@heitorlessa in fact adding e2e tests is a big improvement in the parser area. I just need to check how much data we need to generate in `Kinesis Firehose with PUT source` and `Kinesis Firehose with Kinesis Stream source` to trigger an event in Lambda. I think we should open a new PR to include e2e tests in `v2 branch` while this is not the official branch.

2022-10-03 19:31 UTC, ran-isenberg commented
+1 for E2E tests.
but on the flip side, it's going to make adding new services way harder for newcomers.

2022-10-03 21:04 UTC, leandrodamascena commented
> +1 for E2E tests. but on the flip side, it's going to make adding new services way harder for newcomers.

Yeah Ran, it makes sense and I understand your concern.. But for now we can write e2e tests when someone adds a new service, feature or even extends an existing feature and make life easier for new contributors.

2022-10-04 06:07 UTC, ran-isenberg commented
> > +1 for E2E tests. but on the flip side, it's going to make adding new services way harder for newcomers.
> 
> Yeah Ran, it makes sense and I understand your concern.. But for now we can write e2e tests when someone adds a new service, feature or even extends an existing feature and make life easier for new contributors.

You use CDK right?

2022-10-05 22:36 UTC, leandrodamascena commented
> You use CDK right?

Yeah, we use CDK for e2 testing. But I have some considerations to make about e2e testing before we think about any implementation on Parser.

- e2e tests will only work in v2, so in this PR we should not write end2end tests for the parser.
- We have a release date for v2 later this month and we are working hard for it.
- We believe that only the e2e tests are not enough in all cases. For e.g, if the parser fails for any change in the payload, we run a risk of breaking the function, because it is a runtime error. We need to write a RFC to think of a solution where we can update all lambda eventSources payload every X days/hours, because the payload can change on the service/lambda side and if we don't have the updated project it can be a problem. Maybe a separate project to deal with this, I'm not sure yet, but we'll start that discussion soon.

2022-10-05 22:44 UTC, leandrodamascena requested changes
We need to update the code to account for differences between payloads.

Payload using Kinesis Firehose with a **Kinesis Stream as source**:

```
{
   "invocationId":"77c0024f-9869-4af0-951a-d83c102e8a63",
   "sourceKinesisStreamArn":"arn:aws:kinesis:us-east-1:200984112386:stream/kinesis-evento",
   "deliveryStreamArn":"arn:aws:firehose:us-east-1:200984112386:deliverystream/KDS-S3-10POr",
   "region":"us-east-1",
   "records":[
      {
         "recordId":"49633602406469139358835205474851822974501572780333465650000000",
         "approximateArrivalTimestamp":1664028793294,
         "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg==",
         "kinesisRecordMetadata":{
            "sequenceNumber":"49633602406469139358835205474851822974501572780333465650",
            "subsequenceNumber":0,
            "partitionKey":"0",
            "shardId":"shardId-000000000003",
            "approximateArrivalTimestamp":1664028793294
         }
      },
      {
         "recordId":"49633602406469139358835205474853031900321189264934043698000000",
         "approximateArrivalTimestamp":1664028820148,
         "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg==",
         "kinesisRecordMetadata":{
            "sequenceNumber":"49633602406469139358835205474853031900321189264934043698",
            "subsequenceNumber":0,
            "partitionKey":"0",
            "shardId":"shardId-000000000003",
            "approximateArrivalTimestamp":1664028820148
         }
      }
   ]
}
```

Payload using Kinesis Firehose with **Direct PUT**:
```
{
   "invocationId":"25326478-5c08-45ad-a34d-7342edbc942d",
   "deliveryStreamArn":"arn:aws:firehose:us-east-1:200984112386:deliverystream/PUT-S3-PCYyW",
   "region":"us-east-1",
   "records":[
      {
         "recordId":"49633602747871247603140515133584305740288993709252411394000000",
         "approximateArrivalTimestamp":1664029185290,
         "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg=="
      },
      {
         "recordId":"49633602747871247603140515133585514666108608544585547778000000",
         "approximateArrivalTimestamp":1664029186945,
         "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg=="
      }
   ]
}

```

We can go in the same direction as we went here #1499 and create separate classes for each type of payload.

2022-10-06 05:09 UTC, ran-isenberg commented
> > You use CDK right?
> 
> Yeah, we use CDK for e2 testing. But I have some considerations to make about e2e testing before we think about any implementation on Parser.
> 
> * e2e tests will only work in v2, so in this PR we should not write end2end tests for the parser.
> * We have a release date for v2 later this month and we are working hard for it.
> * We believe that only the e2e tests are not enough in all cases. For e.g, if the parser fails for any change in the payload, we run a risk of breaking the function, because it is a runtime error. We need to write a RFC to think of a solution where we can update all lambda eventSources payload every X days/hours, because the payload can change on the service/lambda side and if we don't have the updated project it can be a problem. Maybe a separate project to deal with this, I'm not sure yet, but we'll start that discussion soon.

The way I'd handle schemas is to put the models in a new repo and maintain proper versions BUT it should be managed and updated by the AWS services, not the community. They should be aware of how we use and model the events since sometime the docs are not good enough. 
If there are any unit/e2e tests, I'd expect the services to run them each time they make a change, some sort of  a  contract test. The E2E tests will run here per PR but you probably wont catch.

2022-10-06 05:11 UTC, ran-isenberg commented
> We need to update the code to account for differences between payloads.
> 
> Payload using Kinesis Firehose with a **Kinesis Stream as source**:
> 
> ```
> {
>    "invocationId":"77c0024f-9869-4af0-951a-d83c102e8a63",
>    "sourceKinesisStreamArn":"arn:aws:kinesis:us-east-1:200984112386:stream/kinesis-evento",
>    "deliveryStreamArn":"arn:aws:firehose:us-east-1:200984112386:deliverystream/KDS-S3-10POr",
>    "region":"us-east-1",
>    "records":[
>       {
>          "recordId":"49633602406469139358835205474851822974501572780333465650000000",
>          "approximateArrivalTimestamp":1664028793294,
>          "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg==",
>          "kinesisRecordMetadata":{
>             "sequenceNumber":"49633602406469139358835205474851822974501572780333465650",
>             "subsequenceNumber":0,
>             "partitionKey":"0",
>             "shardId":"shardId-000000000003",
>             "approximateArrivalTimestamp":1664028793294
>          }
>       },
>       {
>          "recordId":"49633602406469139358835205474853031900321189264934043698000000",
>          "approximateArrivalTimestamp":1664028820148,
>          "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg==",
>          "kinesisRecordMetadata":{
>             "sequenceNumber":"49633602406469139358835205474853031900321189264934043698",
>             "subsequenceNumber":0,
>             "partitionKey":"0",
>             "shardId":"shardId-000000000003",
>             "approximateArrivalTimestamp":1664028820148
>          }
>       }
>    ]
> }
> ```
> 
> Payload using Kinesis Firehose with **Direct PUT**:
> 
> ```
> {
>    "invocationId":"25326478-5c08-45ad-a34d-7342edbc942d",
>    "deliveryStreamArn":"arn:aws:firehose:us-east-1:200984112386:deliverystream/PUT-S3-PCYyW",
>    "region":"us-east-1",
>    "records":[
>       {
>          "recordId":"49633602747871247603140515133584305740288993709252411394000000",
>          "approximateArrivalTimestamp":1664029185290,
>          "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg=="
>       },
>       {
>          "recordId":"49633602747871247603140515133585514666108608544585547778000000",
>          "approximateArrivalTimestamp":1664029186945,
>          "data":"eyJ1c2VyX2lkIjoidXNlcjEiLCAic2NvcmUiOiAxMDB9Cg=="
>       }
>    ]
> }
> ```
> 
> We can go in the same direction as we went here #1499 and create separate classes for each type of payload.

I've modeled the metadata as optional so it works for both cases. The only reason to split them is if it's officially documented as such. do you think that's the case? I didnt find a mention that metadata params are applicable only for put events. If we add by ourselves, it's more likely to be broken in the future.
WDYT?

2022-10-06 13:40 UTC, leandrodamascena commented
> The way I'd handle schemas is to put the models in a new repo and maintain proper versions BUT it should be managed and updated by the AWS services, not the community. They should be aware of how we use and model the events since sometime the docs are not good enough. If there are any unit/e2e tests, I'd expect the services to run them each time they make a change, some sort of a contract test. The E2E tests will run here per PR but you probably wont catch.

I'll open an issue and add this discussion in there, so we can keep focus here in this PR. ok?

2022-10-06 13:48 UTC, ran-isenberg commented
> > The way I'd handle schemas is to put the models in a new repo and maintain proper versions BUT it should be managed and updated by the AWS services, not the community. They should be aware of how we use and model the events since sometime the docs are not good enough. If there are any unit/e2e tests, I'd expect the services to run them each time they make a change, some sort of a contract test. The E2E tests will run here per PR but you probably wont catch.
> 
> I'll open an issue and add this discussion in there, so we can keep focus here in this PR. ok?

No problem.

2022-10-06 14:22 UTC, leandrodamascena requested changes
@ran-isenberg could please check this changes?

2022-10-06 14:22 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/parser/models/kinesis_firehose.py
> +    approximateArrivalTimestamp: int
Even in [documentation](https://docs.aws.amazon.com/lambda/latest/dg/services-kinesisfirehose.html) the field is a string, I created again a kinesis -> kinesis firehose -> lambda and in the service payload this is not a string, this a timestamp field.

![image](https://user-images.githubusercontent.com/4295173/194336065-616fd97b-0c8e-4559-be71-6aaa3d196735.png)

I'll open a ticket to the documentation team to fix that.

2022-10-06 14:22 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/parser/models/kinesis_firehose.py
> +    approximateArrivalTimestamp: int
The reason I changed it to int was: imagine you need to save this information to a database or even needs a timestamp based control, so converting that to datetime might make things difficult.

What do you think? Make sense?

2022-10-06 14:22 UTC, leandrodamascena commented on tests/functional/parser/test_kinesis_firehose.py
> +def handle_firehose_no_envelope_put(event: KinesisFirehoseModel, _: LambdaContext):
New test using PUT payload.

2022-10-06 14:24 UTC, leandrodamascena commented
> I've modeled the metadata as optional so it works for both cases. The only reason to split them is if it's officially documented as such. do you think that's the case? I didnt find a mention that metadata params are applicable only for put events. If we add by ourselves, it's more likely to be broken in the future. WDYT?

I totally agree with you! :100:

2022-10-08 17:17 UTC, ran-isenberg commented on aws_lambda_powertools/utilities/parser/models/kinesis_firehose.py
> +    approximateArrivalTimestamp: int
i think datetime has better validation. I used datetime in all the other models too.
I saw that you changed the example input from a string to an int? is that really the usecase?
If so, then perhaps int is better but you can a datetime validator just to make sure we'r good. I mean, it *is* the parser, so it should offer extra validations.

2022-10-09 10:58 UTC, ran-isenberg commented on aws_lambda_powertools/utilities/parser/models/kinesis_firehose.py
> +    approximateArrivalTimestamp: int
i changed it to positive int to make it extra safer

2022-10-09 11:14 UTC, ran-isenberg commented
@leandrodamascena added my small fix and fixed develop conflict

2022-10-10 10:05 UTC, leandrodamascena approved these changes

2022-10-10 10:06 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/parser/models/kinesis_firehose.py
> +    approximateArrivalTimestamp: int
Good catch, man! :1st_place_medal:

2022-10-10 10:09 UTC, leandrodamascena commented
> @leandrodamascena added my small fix and fixed develop conflict

Heyy good morning and happy monday @ran-isenberg!
If you don't have any other considerations, I think we are good to merge it!
Thanks for addressing all feedback so quickly. :fast_forward:

2022-10-10 10:15 UTC, ran-isenberg commented
LGTM

2022-10-10 10:20 UTC, merged