feat(router): Ignore trailing slashes in APIGatewayRestResolver route resolution
awslabs/aws-lambda-powertools-python pull request #1609
Opened 2022-10-16 11:26 UTC by walmsles

**Issue number:** #1552

**Note Replaces PR:** https://github.com/awslabs/aws-lambda-powertools-python/pull/1577

## Summary

Ingore trailing slash for routers inheriting from APIGatewayResolver

### Changes

AWS API Gateway routes the following 2 paths in the same way "/my/path", "/my/path/", i.e. when routing "/my/path/" it routes exactly as if "/my/path" had been called.  The Lambda Powertools router currently treats these as 2 distinct paths so "/my/path/" returns HTTP statusCode of 404.

### User experience

No change to user experience.  Users will create routes as normal.  In the given sample below making API gateway call to path "/my/path/" will correctly ensure the "get_lambda" route function is correctly called even though it is defined as "/my/path"

```python
app = APIGatewayRestResolver()

    @app.get("/my/path")
    def get_lambda() -> Response:
        assert isinstance(app.current_event, APIGatewayProxyEvent)
        assert app.lambda_context == {}
        assert app.current_event.request_context.domain_name == "id.execute-api.us-east-1.amazonaws.com"
        return Response(200, content_types.APPLICATION_JSON, json.dumps({"foo": "value"}))
```

The code below will work in the same way when called using path "/my/path", "/my/path/"

```python
app = APIGatewayRestResolver()

    @app.get("/my/path/")
    def get_lambda() -> Response:
        assert isinstance(app.current_event, APIGatewayProxyEvent)
        assert app.lambda_context == {}
        assert app.current_event.request_context.domain_name == "id.execute-api.us-east-1.amazonaws.com"
        return Response(200, content_types.APPLICATION_JSON, json.dumps({"foo": "value"}))
```

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/walmsles/aws-lambda-powertools-python/blob/develop/docs/core/event_handler/api_gateway.md)

2022-10-16 22:40 UTC, walmsles commented
I don't get why there are so many conflicts - my actual changes are not that large - will look at rebasing and see if that lowers the madness level.

2022-10-17 05:34 UTC, rubenfonseca commented
@walmsles really sorry about this. As we are getting ready to release v2, we rebased the entire branch from the `develop` branch. Is it possible for you to re-create the PR, cherry-picking the commits into a new v2 fork? We really appreciate your time and effort on this!

2022-10-17 05:57 UTC, walmsles commented
ahhhh, so it's not me, after all, 👀  - I just assumed I was failing hard today 🤣.  No problem - My changes are actually across 2 commits so its very self contained.  Been learning all along so it's all good - not a problem.

2022-10-17 05:59 UTC, walmsles commented
I have hard reset my fork branches to develop/V2 from upstream and re-applied my changes so will see if can edit this PR and make the adjustment and see what it looks like or you think create a new fork is required?

2022-10-17 06:01 UTC, rubenfonseca commented
You can definitely force push into this PR! Thank you so much :)

2022-10-17 06:01 UTC, walmsles commented
> You can definitely force push into this PR! Thank you so much :)

Thankyou 😄 I thought I as going crazy!

2022-10-17 23:39 UTC, walmsles commented
Okay - have managed to wrangle my branches into a fit state of matching upstream now so this is now more sane.

Please refer to [this comment](https://github.com/awslabs/aws-lambda-powertools-python/pull/1577#issuecomment-1279735805) on prior PR.

the TL;DR version:

> I have decided to restrict the implementation of this feature to REST API Gateway (V1) since this is the default behaviour of this gateway implementation for a defined route i.e. both "/hello" and "/hello/" resolve to the same lambda integration. I will write E2E tests covering all the API behaviours around this feature so if anything changes it will be picked up.

(👏 👏 👏 on E2E testing efforts - these are amazing!!!)

2022-10-18 08:37 UTC, heitorlessa commented
Awesome!! Let me know when it's ready to review @walmsles. We're looking to close all V2 activities by tomorrow, and start writing the What's New (new features, non-backward compatible changes, etc.)

2022-10-18 09:20 UTC, walmsles commented
> Awesome!! Let me know when it's ready to review @walmsles. We're looking to close all V2 activities by tomorrow, and start writing the What's New (new features, non-backward compatible changes, etc.)

Hi @heitorlessa, this is ready for review.  I am about to board a flight and will be back online in a couple of hours.

2022-10-18 11:10 UTC, heitorlessa commented
Awesome, looking into this now!

2022-10-18 12:00 UTC, heitorlessa requested changes
Thanks a lot for getting this implemented fast! I'm torn on whether we need an actual route + registration, since we're only testing the additional slash `/` at the end.

I've added some other minor suggestions you can either accept or drop.

2022-10-18 12:00 UTC, heitorlessa commented on aws_lambda_powertools/event_handler/api_gateway.py
> +        # remove trailing "/" character from route rule for correct routing behaviour
```suggestion
        # NOTE: see #1552 for more context.
```

Adding `NOTE` to ease highlighting when reading code. Also a brief mention about the issue for more context, as we already have a comment about trailing on LOC 823.

2022-10-18 12:00 UTC, heitorlessa commented on tests/functional/event_handler/test_api_gateway.py
> +        assert app.current_event.request_context.domain_name == "id.execute-api.us-east-1.amazonaws.com"
```suggestion
```

Correct me if I'm wrong, but I think the value of this test is ensuring we receive a 200 Status Code and this being unnecessary.

2022-10-18 12:00 UTC, heitorlessa commented on tests/functional/event_handler/test_api_gateway.py
> +        assert app.current_event.request_context.elb_target_group_arn is not None
Correct me if I'm wrong, but I think the value of this test is ensuring we receive a 404 Status Code and this being unnecessary.

2022-10-18 12:00 UTC, heitorlessa commented on tests/functional/event_handler/test_api_gateway.py
> +        assert isinstance(app.current_event, APIGatewayProxyEventV2)
```suggestion
```

Correct me if I'm wrong, but I think the value of this test is ensuring we receive a 404 Status Code and this being unnecessary.

2022-10-18 12:00 UTC, heitorlessa commented on tests/functional/event_handler/test_lambda_function_url.py
> +        assert app.current_event.request_context.stage is not None
```suggestion
```

Correct me if I'm wrong, but I think the value of this test is ensuring we receive a 404 Status Code and this being unnecessary.

2022-10-18 12:00 UTC, heitorlessa commented on tests/e2e/event_handler/handlers/alb_handler.py
> +def todos():
thanks for catching that!!!

2022-10-18 12:00 UTC, heitorlessa commented on tests/e2e/event_handler/test_paths_ending_with_slash.py
> +    assert response.content.decode("ascii") == body
you can use `response.text` here.

2022-10-18 12:00 UTC, heitorlessa commented on tests/e2e/event_handler/handlers/api_gateway_http_handler.py
> +    return Response(status_code=200, content_type=content_types.TEXT_PLAIN, body="Hello World")
I'm torn on whether we need another Route instead of reusing `/todos/` with the extra slash, since we're registering it the exact same way - let me know if you think differently.

> we should document this

The reason we use `post` is that whoever writing tests can easily assert on the content being sent (body, headers, cookies, content-type) to reduce cognitive load.

2022-10-18 12:18 UTC, walmsles commented on tests/e2e/event_handler/handlers/api_gateway_http_handler.py
> +    return Response(status_code=200, content_type=content_types.TEXT_PLAIN, body="Hello World")
Agree - let me remove the additional load here and be consistent across all e2e tests which makes sense and will simplify the infrastructure.py as well.

2022-10-18 12:19 UTC, heitorlessa commented on tests/e2e/event_handler/handlers/api_gateway_http_handler.py
> +    return Response(status_code=200, content_type=content_types.TEXT_PLAIN, body="Hello World")
thank you so much!

2022-10-18 12:21 UTC, heitorlessa commented on tests/e2e/event_handler/test_paths_ending_with_slash.py
> +    assert response.content.decode("ascii") == body
```suggestion
    assert response.text == body
```

forgot to add a suggestion to make it easier. `text` property has what you're looking for assertion.

2022-10-18 12:25 UTC, walmsles commented on tests/e2e/event_handler/test_paths_ending_with_slash.py
> +    assert response.content.decode("ascii") == body
will do

2022-10-18 12:25 UTC, walmsles commented on tests/e2e/event_handler/handlers/alb_handler.py
> +def todos():
Welcome (I think github wants me to reply to resolve the conversation)

2022-10-18 12:27 UTC, walmsles commented on tests/e2e/event_handler/test_paths_ending_with_slash.py
> +    assert response.content.decode("ascii") == body
Oh - I already pushed this 🎸

2022-10-18 13:24 UTC, walmsles commented on tests/e2e/event_handler/handlers/api_gateway_http_handler.py
> +    return Response(status_code=200, content_type=content_types.TEXT_PLAIN, body="Hello World")
Have pushed this all just now.  so over to you time for 💤 's

2022-10-18 14:04 UTC, heitorlessa commented on tests/e2e/event_handler/handlers/alb_handler.py
> +# The reason we use post is that whoever is writing tests can easily assert on the
nice!! thank you ;)

2022-10-18 14:05 UTC, heitorlessa commented
LGTM @walmsles. As it's late in ANZ, happy to send the docs and merge it

2022-10-19 06:52 UTC, heitorlessa approved these changes

2022-10-19 06:57 UTC, merged