feat(docs): update docs when creating a new Layer ARN
awslabs/aws-lambda-powertools-python pull request #1610
Opened 2022-10-17 09:56 UTC by rubenfonseca

**Issue number:** #1549

## Summary

This PR automates the publishing of the layer version in our documetation for every release.
This will reduce maintance overhead, and make the publishing of the new layer version faster.

### Changes

> Please provide a summary of what's being changed

- Update action-lint to support multiple nested workflow calls https://github.blog/changelog/2022-08-22-github-actions-improvements-to-reusable-workflows-2/
- Added arm64 layers to docs
- Added method to republish docs after a new published Layer

### User experience

> Please share what the user experience looks like before and after this change

After this change, the new layer version will be update don the documentation automatically, as soon as the Layer is created and published.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-10-17 11:48 UTC, heitorlessa commented on .github/workflows/reusable_publish_v2_layer_arn.yml
> +          git add CHANGELOG.md
docs?

2022-10-17 12:09 UTC, heitorlessa requested changes
two minor issues (git add missing docs, and docs alias) - and one major to add comments on shell script as not everyone is a seasoned bash (and regex) wizardry like you ;D

2022-10-17 12:09 UTC, heitorlessa commented on .github/workflows/reusable_publish_v2_layer_arn.yml
> +name: Publish V2 Layer ARN
Maybe add `docs` in the same so to not be confused with the actual deploy/publish layer

2022-10-17 12:09 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +# This script is run during the reusable_publish_v2_layer_arn CI job,
*docs

2022-10-17 12:09 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +
pr: add more comments on expected input, expected transformation, etc.

2022-10-17 12:09 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +    fi
same as before - more comments on expected input, expected transformation, etc.

might be easier to reference the "canonical" as the Lambda Layers example in various Frameworks (e.g., SAM, SLS, etc.)

and that `eu-central-1` is simply a region that you're picking to get the version and replace each potential **region variation** of a line

2022-10-17 12:09 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +      for region in '{region}' '${AWS::Region}' '${aws:region}' '{env.region}'
```suggestion
      for pseudo_region in '{region}' '${AWS::Region}' '${aws:region}' '{env.region}'
```

pseudo_region = AWS::Region, etc.

2022-10-17 12:09 UTC, heitorlessa commented on .github/workflows/reusable_publish_v2_layer_arn.yml
> +      alias: alpha
```suggestion
      alias: latest
```

2022-10-17 12:16 UTC, rubenfonseca commented
Note: update the rest of the SAM sample code on docs/index.md

2022-10-17 12:16 UTC, rubenfonseca commented
Note: remove "Can't find our Lambda Layer for your preferred AWS region?" because we are now publishing in all regions.

2022-10-17 12:17 UTC, heitorlessa commented
Docs looks excellent. Perhaps let's just increase md-grid (where the content is) to 90vw to give a bit more room, otherwise the layer per region table will look too tight

2022-10-18 08:35 UTC, heitorlessa requested changes
looks great! added last suggestions on var names

2022-10-18 08:35 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +        generic_prefix=$(echo "$prefix" | sed "s/eu-central-1/${pseudo_region}/")
```suggestion
        prefix_pseudo_region=$(echo "$prefix" | sed "s/eu-central-1/${pseudo_region}/")
```

2022-10-18 08:35 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +        generic_line=$(echo "$line" | sed "s/eu-central-1/${pseudo_region}/")
```suggestion
        line_pseudo_region=$(echo "$line" | sed "s/eu-central-1/${pseudo_region}/")
```

2022-10-18 08:35 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +        # generic_line = arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:49
```suggestion
        # line_pseudo_region = arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:49
```

2022-10-18 08:35 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +        # generic_prefix = arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython
```suggestion
        # prefix_pseudo_region = arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython
```

2022-10-18 08:35 UTC, heitorlessa commented on layer/scripts/update_layer_arn.sh
> +        # Replace all the "generic_prefix"'s in the file
```suggestion
        # Replace all the "prefix_pseudo_region"'s in the file
```

2022-10-18 08:36 UTC, heitorlessa commented
Consider it approved after these last changes to ease maintenance.

2022-10-18 08:42 UTC, heitorlessa approved these changes

2022-10-18 08:44 UTC, merged