Added code to deploy with pulumi
awslabs/aws-lambda-powertools-python pull request #1652
Opened 2022-10-25 16:59 UTC by pierskarsenbarg

**Issue number:**

## Summary

Adding code to deploy lambda functions with the lambda layer added (similar PR for typescript here: awslabs/aws-lambda-powertools-typescript#1135)

### Changes

Added Pulumi code both for x86 and arm64 lambda functions

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2022-10-25 17:26 UTC, leandrodamascena commented
Hello @pierskarsenbarg! Thank you so much for opening this PR. I added the "need-issue" and "do-not-merge" labels because we need an issue for every PR we open. 

Don't worry if you don't have time to do it, I can open it on your behalf. I only added the labels so I don't forget about this. 

Thank you.

2022-10-25 20:03 UTC, pierskarsenbarg commented
I will get that done shortly. Thanks for letting me know

2022-10-26 12:26 UTC, leandrodamascena requested changes
Hi @pierskarsenbarg! I made some small changes to fix things. Can you please review and give me your feedback on these changes?

This is an excellent example that will help users adopting AWS/IaC using Pulumi, thank you very much for taking the time to do this. :1st_place_medal:

2022-10-26 12:26 UTC, leandrodamascena commented on docs/index.md
> +                layers=[pulumi.Output.concat("arn:aws:lambda:",aws.get_region_output().name,":017000801446:layer:AWSLambdaPowertoolsPythonV2:11")],
I fixed it. It was using the TS layer.

2022-10-26 12:26 UTC, leandrodamascena commented on docs/index.md
> +                runtime=aws.lambda_.Runtime.PYTHON3D9,
I fixed it. It was using the Node runtime.

2022-10-26 12:26 UTC, leandrodamascena commented on docs/index.md
> +                # other props like code and more...
I removed the `code` property and add this comment. It could cause confusion since we don't have the "app.py" file in this example.

2022-10-26 12:26 UTC, leandrodamascena commented on docs/index.md
> +                runtime=aws.lambda_.Runtime.PYTHON3D9,
I fixed it. It was using the Node runtime.

2022-10-26 12:31 UTC, pierskarsenbarg commented on docs/index.md
> +                # other props like code and more...
I can point it at a zip file like that terraform example if that would help?

2022-10-26 12:31 UTC, pierskarsenbarg commented
All the 🤦 here. Thanks for fixing those

2022-10-26 12:34 UTC, leandrodamascena commented on docs/index.md
> +                # other props like code and more...
Yes, do it! Please use the same name Terraform is using. :rocket:

2022-10-26 12:37 UTC, leandrodamascena commented
> All the facepalm here. Thanks for fixing those

Don't worry! I know some days are really hard when working with software development :smile: .

2022-10-26 13:03 UTC, pierskarsenbarg commented
Yes it was definitely one of those days

2022-10-26 14:42 UTC, leandrodamascena approved these changes
Approved!

2022-10-26 14:43 UTC, pierskarsenbarg commented
So do I merge this? Do you merge it? What's next?

2022-10-26 14:47 UTC, merged

2022-10-26 14:47 UTC, leandrodamascena commented
> So do I merge this? Do you merge it? What's next?

Yeahhhh! Merged!!