feat(event_handlers) Add support for returning dict, status-code tuples from resolvers
awslabs/aws-lambda-powertools-python pull request #1853
Opened 2023-01-23 16:33 UTC by theoutsider24

**Issue number:**
#1845

## Summary

### Changes

The response handling in api gateway has been extended to handle dict, status-code tuples

### User experience

Endpoints with non-200 status code no longer need to manually build Response objects, they can simply return a dict and status code

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>
No

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-01-23 16:39 UTC, rubenfonseca requested changes
@theoutsider24 thank you for opening this PR!

Two asks:
- can you please try to fix the tests? I believe we need some type updates to the tests
- would you mind adding an update to the docs with the new use case?

We would love if you could help us with this, but otherwise we would be happy to assist :)

2023-01-23 17:02 UTC, theoutsider24 commented
@rubenfonseca Thanks for the comments! 

I've fixed that issue with the type-hinting
Regarding the docs - where do you think the most appropriate place would be to mention it? I couldn't see a place that seemed obvious so I just included it in some existing examples that seemed relevant

2023-01-24 11:50 UTC, rubenfonseca approved these changes

2023-01-24 11:50 UTC, merged

2023-01-24 11:51 UTC, leandrodamascena commented
Thank you so much for this PR @theoutsider24! Ruben updated the documentation and we merged it!

2023-01-24 11:57 UTC, theoutsider24 commented
That's awesome! Thanks so much for your help guys, really pleased I was able to contribute and I look forward to using the feature myself 💪

2023-01-24 14:33 UTC, rubenfonseca commented
This is now released under [2.7.0](https://github.com/awslabs/aws-lambda-powertools-python/releases/tag/v2.7.0) version!