feat(data_classes): API Gateway V2 IAM and Lambda
awslabs/aws-lambda-powertools-python pull request #201
Opened 2020-10-31 08:13 UTC by michaelbrewer

**Issue #, if available:**

## Description of changes:

Update to support IAM and Lambda authorizer for API
Gateway V2 trigger events

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-02 07:32 UTC, heitorlessa requested changes
LGTM except missing docstrings in certain properties for consistency

2020-11-02 07:32 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +    def cognito_amr(self) -> Optional[List[str]]:
could you add a docstring here?

2020-11-02 07:32 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +    def access_key(self) -> Optional[str]:
could you add a docstring here?

2020-11-02 07:32 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +    def user_id(self) -> Optional[str]:
could you add a docstring here?

2020-11-02 07:32 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +    def get_lambda(self) -> Optional[Dict[str, Any]]:
could you add a docstring here?

2020-11-02 07:32 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_proxy_event.py
> +    def iam(self) -> Optional[RequestContextV2AuthorizerIam]:
could you add a docstring here?

2020-11-02 10:46 UTC, michaelbrewer commented
@heitorlessa - made those changes. I did have to did around into the cognito docs for some of them and parts of the IAM / Lambda authorizers docs

2020-11-03 14:48 UTC, heitorlessa approved these changes

2020-11-03 14:48 UTC, heitorlessa commented
Looks great, thanks for those again @michaelbrewer !!

2020-11-03 14:48 UTC, merged