feat(logger): add flush_metrics
awslabs/aws-lambda-powertools-python pull request #2171
Opened 2023-04-27 13:23 UTC by rubenfonseca

**Issue number:** #2109

## Summary

### Changes

> Please provide a summary of what's being changed

This PR adds a new `flush_metrics` to the metrics utility to manually flush the metrics.

### User experience

> Please share what the user experience looks like before and after this change

Before this PR it was hard for users of the metrics utility to flush the metrics when not running on the Lambda runtime. This simple refactor enables the users
quick access to manually flushing the metrics.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

- [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [x] I have performed a self-review of this change
- [x] Changes have been tested
- [x] Changes are documented
- [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

- [ ] Migration process documented
- [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-04-27 13:27 UTC, rubenfonseca commented on examples/metrics/src/flush_metrics.py
This example file was not being used in the documentation, so I just changed the content and started using it.

2023-04-27 16:52 UTC, leandrodamascena reviewed
Another excellent job Rubens!!

I'm wondering if we should do the same as the typescript and move the "Flushing metrics manually" topic to the "Flushing Metrics" menu. What do you think about?

Reference:
https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/metrics/#manually

![image](https://user-images.githubusercontent.com/4295173/234934110-2b219982-4f2e-416c-8477-0edafa464b9c.png)

2023-04-28 09:52 UTC, rubenfonseca commented
Peer-review feedback:

- remove single metric example
- expand the example with try/catch to handle uncaught exceptions when manually flushing metrics

2023-04-28 13:15 UTC, heitorlessa requested changes
dummy logic to try/finally makes more sense

2023-04-28 13:15 UTC, heitorlessa commented on examples/metrics/src/flush_metrics.py
>  def lambda_handler(event: dict, context: LambdaContext):
```suggestion
def book_flight(flight_id: str, **kwargs): 
    # logic to book flight
    ...
    metrics.add_metric(name="SuccessfulBooking", unit=MetricUnit.Count, value=1)


def lambda_handler(event: dict, context: LambdaContext):
```

2023-04-28 13:15 UTC, heitorlessa commented on examples/metrics/src/flush_metrics.py
> +        metrics.add_metric(name="SuccessfulBooking", unit=MetricUnit.Count, value=1)
```suggestion
        book_flight(flight_id=event.get("flight_id", ""))
```

2023-04-28 13:40 UTC, leandrodamascena approved these changes
Approved :)
![image](https://user-images.githubusercontent.com/4295173/235163254-dc0d70ad-8a7d-4437-8cd1-41b4af21833a.png)

2023-04-28 13:46 UTC, merged