feat(event_sources): add AWS Config Rule event data class
awslabs/aws-lambda-powertools-python pull request #2175
Opened 2023-04-27 23:10 UTC by leandrodamascena

**Issue number:** #1667 

## Summary

### Changes

In this PR we are adding the 3 types of events that can trigger a Lambda from an AWS Config rule.

These events are:

- **ConfigurationItemChangeNotification** - AWS Config publishes an event when it detects a configuration change for a resource that is within the scope of a rule.
- **ScheduledNotification** - AWS Config publishes an event when it evaluates your resources at a frequency that you specify (such as every 1 hour)
- **OversizedConfigurationItemChangeNotification** - Some resource changes generate oversized configuration items

### User experience

**BEFORE**

```python
from aws_lambda_powertools.utilities.typing import LambdaContext
from aws_lambda_powertools import Logger
import json

logger = Logger()

def lambda_handler(event, context: LambdaContext):

    message_type = json.loads(event["invokingEvent"])["messageType"]

    logger.info(f"Logging {message_type} event rule", invoke_event=event["invokingEvent"])

    return {"Success": "OK"}
```

**AFTER**

```python
from aws_lambda_powertools.utilities.data_classes import AWSConfigRuleEvent, event_source
from aws_lambda_powertools.utilities.typing import LambdaContext
from aws_lambda_powertools import Logger

logger = Logger()

@event_source(data_class=AWSConfigRuleEvent)
def lambda_handler(event: AWSConfigRuleEvent, context: LambdaContext):

    message_type = event.invoking_event.message_type

    logger.info(f"Logging {message_type} event rule", invoke_event=event.raw_invoking_event)

    return {"Success": "OK"}
```

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-05-01 08:41 UTC, rubenfonseca requested changes
That's a lot of great work! Just left a small change in the highlights of the docs.

2023-05-01 08:41 UTC, rubenfonseca commented on docs/utilities/data_classes.md
> +    ```python hl_lines="1 7"
```suggestion
    ```python hl_lines="3 11"
```

2023-05-01 18:02 UTC, leandrodamascena commented on docs/utilities/data_classes.md
> +    ```python hl_lines="1 7"
Done

2023-05-31 10:14 UTC, austindimmer commented
This looks great, I was running in to this issue yesterday whilst building my first Custom Config rule and was about to build my own data structure to handle the incoming events. This looks to be exactly what is needed.

I look forward to this being merged. 

Thanks for the efforts!

2023-05-31 20:12 UTC, leandrodamascena commented
> This looks great, I was running in to this issue yesterday whilst building my first Custom Config rule and was about to build my own data structure to handle the incoming events. This looks to be exactly what is needed.
> 
> I look forward to this being merged.
> 
> Thanks for the efforts!

Hi @austindimmer! It's amazing to hear that. We are reaching out to the AWS Config team just to confirm some information about these schemas, but we will definitely do our best to get this merged as soon as possible.

Thanks.

2023-06-15 13:00 UTC, leandrodamascena commented
Hey, everyone! We haven't received any updates from the AWS Config team regarding event/schema validation and are moving forward with this PR.
To ensure this new `EventSource class` works as expected, we've tested extensively with many events and payloads, and in all cases, we've had success using this.

Until we get feedback from our customers that this feature is working as expected, we will not be adding Parser support.

@rubenfonseca, can you review this, please?

2023-06-15 14:32 UTC, rubenfonseca approved these changes
This looks amazing, thank you for the great work @leandrodamascena !

2023-06-15 14:32 UTC, merged