docs(feature_flags): snippets split, improved, and lint
awslabs/aws-lambda-powertools-python pull request #2222
Opened 2023-05-07 20:59 UTC by leandrodamascena

**Issue number:** #1373 

## Summary

Changes snippet fictitious names to real code snippet filenames for easier discovery and collaboration to improve/correct document snippets.

Some examples have also been refactored so that the codes are complete and there are no lint/pre-commit hooks issues.

> Please provide a summary of what's being changed

### User experience

**BEFORE**
![image](https://user-images.githubusercontent.com/4295173/236702273-950d39f2-80c0-40ae-9820-5ec5f76b9f90.png)

**AFTER**
![image](https://user-images.githubusercontent.com/4295173/236702282-56c8f6f2-2ad5-4229-957f-e31ea8b51585.png)

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-05-10 12:06 UTC, rubenfonseca commented
Will review this later today

2023-05-11 13:14 UTC, rubenfonseca requested changes
I pushed two small fixes and left two comments to think about. Great great work Leandro!

2023-05-11 13:14 UTC, rubenfonseca commented on docs/utilities/feature_flags.md
> +* Bring Your Own Feature Flags Store Provider
```suggestion
* Bring your own Feature Flags store provider
```
Just to make it consistent with the other bullet points?

2023-05-11 13:14 UTC, rubenfonseca commented on docs/utilities/feature_flags.md
> +You can create your own custom FeatureFlags store provider by inheriting the `StoreProvider` class, and implementing both `get_raw_configuration()` and `get_configuration()` methods to retrieve the c
When reading the text and the sample, I don't understand what's the difference between the two methods `get_raw_configuration` and `get_configuration`. Do you think we can expand a little bit on that?

2023-05-11 18:21 UTC, leandrodamascena commented on docs/utilities/feature_flags.md
> +* Bring Your Own Feature Flags Store Provider
Done

2023-05-11 18:22 UTC, leandrodamascena commented on docs/utilities/feature_flags.md
> +You can create your own custom FeatureFlags store provider by inheriting the `StoreProvider` class, and implementing both `get_raw_configuration()` and `get_configuration()` methods to retrieve the c
In fact, we need to explain this in a little more detail, just as you did in batch processing.

I did this, can you check pls?

2023-05-16 09:24 UTC, rubenfonseca approved these changes
Loved the changes explaining the `get` vs `get_raw`. Thank you for this awesome work Leo!

2023-05-16 09:26 UTC, merged