chore(docs): refactor batch processing code snippets
awslabs/aws-lambda-powertools-python pull request #2231
Opened 2023-05-09 13:22 UTC by rubenfonseca

**Issue number:** #1369

## Summary

### Changes

> Please provide a summary of what's being changed

This PR extracts, fixes and refactors all code snippets for the batch utility.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

- [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [x] I have performed a self-review of this change
- [x] Changes have been tested
- [x] Changes are documented
- [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

- [ ] Migration process documented
- [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-05-09 20:26 UTC, leandrodamascena commented
Hey @rubenfonseca! I'm starting the initial review and should have it wrapped up in the next 1-2 days.

2023-05-09 21:19 UTC, leandrodamascena requested changes
Hi @rubenfonseca! This is an incredible amount of work! I made some suggestions on things I found out.

btw, I pushed 2 commits with changes to correct things that I detected in the `batch.md` file.

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/sam/dynamodb_batch_processing.yaml
> +    Runtime: python3.9
```suggestion
    Runtime: python3.10
```

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/sam/kinesis_batch_processing.yaml
> +    Runtime: python3.9
```suggestion
    Runtime: python3.10
```

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/sam/sqs_batch_processing.yaml
> +    Runtime: python3.9
```suggestion
    Runtime: python3.10
```

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/src/advanced_accessing_lambda_context.py
> -    ...
Ruben, pls demonstrate how to access `lambda_context` here. Same as you did in other examples.

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/src/extending_failure.py
Missing highlight in this example.

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/src/custom_partial_processor.py
> +    return {"statusCode": 200}
Should we use the new Recommended method instead of the decorator?

2023-05-09 21:19 UTC, leandrodamascena commented on examples/batch_processing/src/disable_tracing.py
> +    return processor.response()
Should we use the new Recommended method instead of the decorator?

2023-05-10 11:44 UTC, rubenfonseca commented on examples/batch_processing/src/advanced_accessing_lambda_context.py
> -    ...
Great catch! Fixed

2023-05-10 12:05 UTC, rubenfonseca commented
@leandrodamascena ready for round 2

2023-05-10 23:26 UTC, leandrodamascena commented on examples/batch_processing/testing/src/__init__.py
Oh mypy!!! WHY?? :cry: 

I'll move this to the parent folder.

```sh
poetry run mypy --pretty aws_lambda_powertools examples
examples/parameters/tests/src/__init__.py: error: Duplicate module named "src" (also at "examples/batch_processing/testing/src/__init__.py")
examples/parameters/tests/src/__init__.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
examples/parameters/tests/src/__init__.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
Found 1 error in 1 file (errors prevented further checking)

```

2023-05-10 23:46 UTC, leandrodamascena requested changes
Hi @rubenfonseca! Since you are at the Summit this week and I don't want to bother you with minor changes, I pushed 1 commit with some changes.

Please check if it makes sense, if it does, for me this PR is approved!! One more GREAT job man!

2023-05-10 23:46 UTC, leandrodamascena commented on docs/utilities/batch.md
> +
Added an event payload because this payload is very specific and must be a dict to make Pydantic work.

2023-05-10 23:46 UTC, leandrodamascena commented on docs/utilities/batch.md
> +    ```
Added an event payload because this payload is very specific and must be a dict to make Pydantic work.

2023-05-10 23:46 UTC, leandrodamascena commented on docs/utilities/batch.md
> +    ```
Added an event payload because this payload is very specific and must be a dict to make Pydantic work.

2023-05-10 23:46 UTC, leandrodamascena commented on docs/utilities/batch.md
>      ```
Moved to the parent folder due to mypy complaints.

2023-05-10 23:46 UTC, leandrodamascena commented on examples/batch_processing/src/context_manager_access.py
> +        logger.info(status, record=record)
Sometimes `result` was None and the logger can't parse this.

2023-05-11 10:45 UTC, rubenfonseca commented
@leandrodamascena changes look good! I've made a quick fix to one of the highlights, and for me it's good to merge :)

2023-05-11 11:19 UTC, leandrodamascena approved these changes
APPROVED!!!
![image](https://github.com/awslabs/aws-lambda-powertools-python/assets/4295173/b202c115-a607-4758-aeeb-70a997b19268)

2023-05-11 11:21 UTC, merged