feat: Add cloudwatch lambda event support to Parser utility
awslabs/aws-lambda-powertools-python pull request #231
Opened 2020-12-01 08:36 UTC by risenberg-cyberark

see #230

2020-12-01 09:04 UTC, heitorlessa requested changes
Looks great! Minor suggestions and one question on zlib header/trailer size param.

As with other PRs, I'll write the docs afterwards ;)

2020-12-01 09:04 UTC, heitorlessa commented on aws_lambda_powertools/utilities/parser/models/cloudwatch.py
> +            return json.loads(uncompressed.decode("UTF-8"))
```suggestion
            return json.loads(uncompressed.decode("utf-8"))
```

2020-12-01 09:04 UTC, heitorlessa commented on tests/functional/parser/test_cloudwatch.py
> +@event_parser(model=MyCloudWatchBusiness, envelope=envelopes.CloudatchEnvelope)
```suggestion
@event_parser(model=MyCloudWatchBusiness, envelope=envelopes.CloudatchLogsEnvelope)
```

2020-12-01 14:06 UTC, risenberg-cyberark commented on aws_lambda_powertools/utilities/parser/models/cloudwatch.py
> +            uncompressed = zlib.decompress(payload, zlib.MAX_WBITS | 32)
didnt work without it

2020-12-04 13:17 UTC, heitorlessa approved these changes
Docs added and envelope type fixed - Merging

2020-12-04 13:17 UTC, merged