Fix/batch processing exceptions
awslabs/aws-lambda-powertools-python pull request #276
Opened 2021-01-26 14:22 UTC by cakepietoast

**Issue #, if available:** #275

## Description of changes:

Update batch exception handling to include more detail of the actual exceptions raised in users processing code.

_Why not just log the exception one-by-one as we catch them?_
By default, the aws_lambda_powertools package logger is suppressed. Logging from package modules would require users to take [additional steps](https://awslabs.github.io/aws-lambda-powertools-python/#debug-mode) to see those logs.

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-26 17:55 UTC, heitorlessa commented
Will look into it tomorrow :)

On Tue, 26 Jan 2021 at 16:46, Tom McCarthy <notifications@github.com> wrote:

> @cakepietoast <https://github.com/cakepietoast> requested your review on:
> #276 <https://github.com/awslabs/aws-lambda-powertools-python/pull/276>
> fix: batch processing exceptions.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/276#event-4251350092>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBGRLATUQJDBVHUVBZDS33PVNANCNFSM4WTQ7Z2A>
> .
>

2021-02-01 09:33 UTC, heitorlessa commented
I'm late on reviewing this... I'll try tomorrow evening - Been a roller-coaster these past days

2021-02-02 16:43 UTC, heitorlessa requested changes
LGTM - minor changes so we remember why we're making some of these changes, and not a generic exception processing class

2021-02-02 16:43 UTC, heitorlessa commented on aws_lambda_powertools/utilities/batch/exceptions.py
> +        parent_exception_str = super(SQSBatchProcessingError, self).__str__()
Could you add a comment as to why we're doing this? Maybe a ref to the issue, so it's easier to remember why

2021-02-02 16:43 UTC, heitorlessa commented on aws_lambda_powertools/utilities/batch/sqs.py
> +            return self.failure_handler(record, sys.exc_info())
nitpick: could you use kwargs in case we refactor in the future?

2021-02-02 17:00 UTC, cakepietoast commented
Implemented requested changes from review

2021-02-02 17:02 UTC, merged