feat: add support for Python 3.11
awslabs/aws-lambda-powertools-python pull request #2820
Opened 2023-07-21 16:17 UTC by rubenfonseca

**Issue number:** #2732

## Summary

This PR adds support for Python 3.11.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

- [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
- [x] I have performed a self-review of this change
- [x] Changes have been tested
- [x] Changes are documented
- [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

- [ ] Migration process documented
- [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-07-21 16:19 UTC, heitorlessa approved these changes

2023-07-21 16:24 UTC, rubenfonseca commented
TODO: remove snappy dependency and all references in examples and documentation /cc @leandrodamascena

2023-07-23 10:00 UTC, leandrodamascena requested changes
I added some important information I found on this PR before we merged.

2023-07-23 10:00 UTC, leandrodamascena commented on tests/functional/validator/test_validator.py
> +    message = "data must contain ['username'] properties"
fastjsonschema changed the way of reporting bugs in the latest version (2.18.0). Now it just reports missing fields instead of all fields.

https://github.com/horejsek/python-fastjsonschema/commit/756540088687cda351390f687b92e602feaa7dc6

> * Improved error message for required props - only missing are reported

2023-07-23 10:00 UTC, leandrodamascena commented on tests/unit/test_lru_cache.py
> +        pytest.fail("GitHub #300: LRUDict pop bug has been fixed.")
NOTE: I removed some characters to allow for adding a comment.

First time I had contact with this and the test is falling. I understand why it's failing in Python 3.11, but I have no idea why we need it here. Do you have any information about this worth sharing @heitorlessa?

ERROR:

>          > pytest.fail("GitHub #300: LRUDict pop bug has been fixed.")
>          E Failed: GitHub #300: LRUDict pop bug has been fixed.

2023-07-23 10:00 UTC, leandrodamascena commented on pyproject.toml
> -python-snappy = "^0.6.1"
I'll recreate the example that use this library.

2023-07-23 13:47 UTC, leandrodamascena commented on pyproject.toml
> -python-snappy = "^0.6.1"
The example is using zlib instead snappy.

2023-07-23 19:09 UTC, leandrodamascena commented
Can't update the examples because cfn-lint still doesn't offer support to Python 3.11

```sh
linting::cloudformation..................................................Failed
- hook id: cloudformation
- exit code: 2

E3030 You must specify a valid value for Runtime (python3.11). Valid values are ["dotnet6", "dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java17", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x", "nodejs16.x", "nodejs18.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.10", "python3.6", "python3.7", "python3.8", "python3.9", "ruby2.5", "ruby2.7", "ruby3.2"]
examples/batch_processing/sam/dynamodb_batch_processing.yaml:17:3
```

There is an issue to add support for this - https://github.com/aws-cloudformation/cfn-lint/issues/2788

2023-07-23 19:18 UTC, leandrodamascena commented
Hello @rubenfonseca! This is a HUGE amount of incredible WORK! We can merge this PR merge after @heitorlessa help us with a small problem in one of our tests.

Congrats dude, this is an essential step for us. :rocket: :heart:

2023-07-24 09:49 UTC, heitorlessa commented on tests/unit/test_lru_cache.py
> +        pytest.fail("GitHub #300: LRUDict pop bug has been fixed.")
That was an old bug in the implementation of LRUDict from `OrderedDict`. Let's skip for 3.11+ until we have more quality time to dive into refactoring this.

2023-07-24 11:46 UTC, leandrodamascena commented on tests/unit/test_lru_cache.py
> +        pytest.fail("GitHub #300: LRUDict pop bug has been fixed.")
Added a skip for Python 3.11+.

2023-07-24 12:12 UTC, heitorlessa approved these changes

2023-07-24 12:13 UTC, heitorlessa commented
Thank you @rubenfonseca and @leandrodamascena - fantastic work ;)

2023-07-24 12:16 UTC, leandrodamascena approved these changes

2023-07-24 12:18 UTC, merged