feat(idempotencty): Raise error when event data is None
awslabs/aws-lambda-powertools-python pull request #297
Opened 2021-02-22 03:05 UTC by michaelbrewer

**Issue #, if available:**

## Description of changes:

GIVEN a persistence_store with event_key_jmespath = `body`
WHEN getting the hashed idempotency key with an event without a `body` key
THEN raise IdempotencyValidationError

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

Raising any kind of error when not passing in the data for the idemptency data is not what we currently do

2021-02-22 03:07 UTC, michaelbrewer commented
@cakepietoast  @heitorlessa  - you might want to debate this.

For example when `event_key_jmespath = "[body, queryStringParameters]"`
and the event is `{}` then the `data` is `[None, None]`

2021-02-22 06:22 UTC, michaelbrewer commented
> @cakepietoast @heitorlessa - you might want to debate this.
> 
> For example when `event_key_jmespath = "[body, queryStringParameters]"`
> and the event is `{}` then the `data` is `[None, None]`

Also if we do raise an error, should it be a new type for Idempotency key errors?

2021-02-25 11:36 UTC, michaelbrewer commented
@heitorlessa @cakepietoast  - i added a `raise_on_no_idempotency_key` option and a new new exception `IdempotencyKeyError`

2021-03-02 13:58 UTC, heitorlessa commented
I’ll look into this tomorrow morning and update here as soon as I can.

On Tue, 2 Mar 2021 at 14:49, Michael Brewer <notifications@github.com>
wrote:

> @heitorlessa <https://github.com/heitorlessa> any concerns or changes
> needed for this PR ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/297#issuecomment-788922138>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBGI5BSLL64OLRLETILTBTUHDANCNFSM4X7V2Q3A>
> .
>

2021-03-03 12:49 UTC, heitorlessa commented
Checking this now

2021-03-03 13:10 UTC, heitorlessa requested changes
LGTM after logic to catch iterables like empty tuple and dicts as well as doc

2021-03-03 13:10 UTC, heitorlessa commented on aws_lambda_powertools/utilities/idempotency/persistence/base.py
> +        return data is None or (type(data) is list and all(x is None for x in data))
```suggestion
        return data is None or not data or all(x is None for x in data)
```

This accounts for empty data structures, including non-lists iterables like tuples, dictionaries

2021-03-03 13:10 UTC, heitorlessa commented on tests/functional/idempotency/test_idempotency.py
> +
```suggestion
    assert BasePersistenceLayer.is_missing_idempotency_key("Value") is False

    assert BasePersistenceLayer.is_missing_idempotency_key(()) is False
    # GIVEN an empty dictionary THEN is_missing_idempotency_key is false
    assert BasePersistenceLayer.is_missing_idempotency_key({}) is False
```

Add tests for non-lists but iterable too

2021-03-03 13:10 UTC, heitorlessa commented on docs/utilities/idempotency.md
> +If you want to ensure that at an idempotency is found, you can pass in `raise_on_no_idempotency_key` as True and an
Not sure what you mean by "If you want to ensure that at an idempotency is found" - could you simplify this to non-native English speakers, please?

2021-03-03 13:49 UTC, heitorlessa approved these changes

2021-03-03 13:49 UTC, heitorlessa commented
Merging it - Thanks a lot @michaelbrewer 🎉

2021-03-03 13:50 UTC, merged