docs(event_handler): Highlight case-insensitive lookup of headers
awslabs/aws-lambda-powertools-python pull request #3183
Opened 2023-10-08 22:07 UTC by pgrzesik

**Issue number:** #3142 

## Summary

Slightly improved documentation about case-insensitive lookup of specific header values for REST API events.

### Changes

As above, slight changes to docs only

### User experience

Improved documentation

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [ ] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-10-09 10:54 UTC, leandrodamascena requested changes
Hi @pgrzesik! I left a comment with a suggestion to transform the text into a more active voice and tell the customer what they should do to achieve the result they want. Make sense?
Thank you for sending this PR. Improving our documentation from customer feedback is something we work hard on every day.

2023-10-09 10:54 UTC, leandrodamascena commented on docs/core/event_handler/api_gateway.md
> +Similarly to [Query strings](#query-strings-and-payload), you can access headers as dictionary via `app.current_event.headers`, or by name via `get_header_value`. If you'd like to perform a case-inse
```suggestion
Similarly to [Query strings](#query-strings-and-payload), you can access headers as dictionary via `app.current_event.headers`, or by name via `get_header_value`. If you prefer a case-insensitive lookup of the header value, the get_header_value utility function automatically handles it.
```

2023-10-10 20:58 UTC, pgrzesik commented
Thank you for the suggestion @leandrodamascena, I just accepted it 🙌

2023-10-10 21:42 UTC, leandrodamascena approved these changes, later dismissed
Hi @pgrzesik! This PR seems simple because we just changed a line, but the discussions that brought us here were complex and you could find a simple and effective solution. This is priceless, we really appreciate this.

Approved!

![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/32cd0a95-2896-40b9-8fae-c6aa46763949)

2023-10-10 21:43 UTC, leandrodamascena approved these changes, later dismissed

2023-10-11 08:10 UTC, heitorlessa commented on docs/core/event_handler/api_gateway.md
> +Similarly to [Query strings](#query-strings-and-payload), you can access headers as dictionary via `app.current_event.headers`, or by name via `get_header_value`. If you prefer a case-insensitive loo
```suggestion
Similarly to [Query strings](#query-strings-and-payload), you can access headers as dictionary via `app.current_event.headers`, or by name via `get_header_value`. If you prefer a case-insensitive lookup of the header value, the `app.current_event.get_header_value` function automatically handles it.
```

2023-10-11 08:12 UTC, heitorlessa requested changes
looks great, thank you so much @pgrzesik!

@leandrodamascena before we merge, we need to fix the docstring in the `get_header_value` function to signal that *by default we make a case-insensitive lookup**

2023-10-11 10:19 UTC, leandrodamascena commented
> looks great, thank you so much @pgrzesik!
> 
> @leandrodamascena before we merge, we need to fix the docstring in the `get_header_value` function to signal that _by default we make a case-insensitive lookup_*

Hey @heitorlessa - https://github.com/aws-powertools/powertools-lambda-python/pull/3183/files#diff-201518b4cf27a31cff68870554e0b4e2d6de2fa18456d2ea85d04d156991600cR192

2023-10-11 10:24 UTC, heitorlessa approved these changes

2023-10-11 10:37 UTC, merged