refactor(parameters): Consistently reference env
awslabs/aws-lambda-powertools-python pull request #319
Opened 2021-03-08 19:23 UTC by michaelbrewer

**Issue #, if available:**

## Description of changes:

Use the defined constants to look up service name environment variable

NOTE: This does now defaults to `service_undefined`

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-08 19:25 UTC, michaelbrewer commented
Sorry @heitorlessa  i botched the commit message.

2021-03-09 13:49 UTC, heitorlessa requested changes
Thanks a lot Michael for fixing one more internal bit. I've added the new `resolve_env_var_choice` to ensure correctness and consistency across others.

2021-03-09 13:49 UTC, heitorlessa commented on aws_lambda_powertools/utilities/parameters/appconfig.py
> +        self.application = application or os.getenv(constants.SERVICE_NAME_ENV, "service_undefined")
You can use the new function we created to enforce explicit over env var, etc. 

```suggestion
        self.application = resolve_env_var_choice(choice=application, env=os.getenv(constants.SERVICE_NAME_ENV, "service_undefined"))
```

2021-03-09 14:52 UTC, heitorlessa approved these changes

2021-03-09 14:53 UTC, merged