refactor(parameters): Add overload signatures for get_parameter and get_parameters
awslabs/aws-lambda-powertools-python pull request #3534
Opened 2023-12-18 16:56 UTC by troyswanson

**Issue number: #3507**

## Summary

### Changes

Adds overload signatures for the `get_parameter` and `get_parameters` functions depending on the arguments present. Also defines the literals that are available in the `transform` argument.

### User experience

Type checkers should return the expected type based on the value in the `transform` argument.

* If `None`, return type should be `str`
* If `"json"`, return type should be `dict`
* If `"binary"`, return type should be `bytes`

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>
No
</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2023-12-19 14:47 UTC, rubenfonseca commented
Looking at this now

2023-12-19 15:17 UTC, heitorlessa requested changes, later dismissed
great work!!! Only one missing... `Literal["auto"]`. [It uses the parameter suffix](https://docs.powertools.aws.dev/lambda/python/latest/utilities/parameters/#auto-transform-values-on-suffix) to find the transformation method to use (`.binary` -> Binary, or `.json` -> JSON).

Example in [`get_parameters_by_name`](https://github.com/aws-powertools/powertools-lambda-python/blob/76217cd22b284b2ba7f232f83ad2b6bf58d12363/aws_lambda_powertools/utilities/parameters/ssm.py#L753).

2023-12-20 13:56 UTC, rubenfonseca commented
I've added the missing case. @heitorlessa please review when possible

2023-12-20 14:02 UTC, leandrodamascena approved these changes, later dismissed
APPROVED

2023-12-20 14:41 UTC, heitorlessa approved these changes, later dismissed

2023-12-20 16:04 UTC, rubenfonseca approved these changes

2023-12-20 16:05 UTC, merged