docs(event-handler): add section about problems when using SwaggerUI and cache
awslabs/aws-lambda-powertools-python pull request #3562
Opened 2023-12-26 16:20 UTC by leandrodamascena

**Issue number:** #3552 

## Summary

### Changes

This pull request focuses on highlighting and documenting the challenges associated with {proxy+} caching and removing unnecessary `sourceMappingURL` configuration.

### User experience

No changes in the use experience.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-01-09 13:58 UTC, rubenfonseca submitted a review, later dismissed

2024-01-09 16:20 UTC, rubenfonseca requested changes, later dismissed
I believe we also need to update the docs to remove the references to swagger.css and swagger.js?

2024-01-09 16:50 UTC, rubenfonseca approved these changes, later dismissed

2024-01-09 16:58 UTC, leandrodamascena commented
> I believe we also need to update the docs to remove the references to swagger.css and swagger.js?

You're right, Ruben! There was some reference to /swagger.js and CSS.. I removed it completely.

2024-01-10 09:08 UTC, rubenfonseca requested changes
Sorry, just a small thing

2024-01-10 09:08 UTC, rubenfonseca commented on docs/core/event_handler/api_gateway.md
> +| You need to expose **new route**                 | You'll need to expose the following paths to Lambda: `/swagger`; ignore if you're routing this path already.                        |
```suggestion
| You need to expose a **new route**               | You'll need to expose the following path to Lambda: `/swagger`; ignore if you're routing this path already.                         |
```

2024-01-10 10:25 UTC, leandrodamascena commented
> Sorry, just a small thing

Ready to review.

2024-01-10 13:36 UTC, rubenfonseca approved these changes

2024-01-10 13:46 UTC, merged