feat(event_handler): use custom serializer during openapi serialization
awslabs/aws-lambda-powertools-python pull request #3900
Opened 2024-03-07 13:53 UTC by rubenfonseca

**Issue number:** #3892

## Summary

### Changes

> Please provide a summary of what's being changed

This PR modifies the OpenAPI validation middleware to use the any custom serialized provided by the user on the event handler, when the normal serialization mechanisms fail.

This allows you to use your own custom serializer when returning custom objects
from the handlers.

### User experience

> Please share what the user experience looks like before and after this change

```python
def test_openapi_serialize_other(gw_event):
    # GIVEN a custom serializer
    def serializer(_):
        return "hello world"

    # GIVEN APIGatewayRestResolver is initialized with enable_validation=True and the custom serializer
    app = APIGatewayRestResolver(enable_validation=True, serializer=serializer)

    # GIVEN a custom class
    class CustomClass(object):
        __slots__ = []

    # GIVEN a handler that returns an instance of that class
    @app.get("/my/path")
    def handler():
        return CustomClass()

    # WHEN we invoke the handler
    response = app(gw_event, {})

    # THEN we the custom serializer should be used
    assert response["body"] == "hello world"
```

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-03-07 14:09 UTC, sthulb approved these changes, later dismissed

2024-03-07 20:00 UTC, leandrodamascena requested changes
Hello @rubenfonseca! I just left some small suggestions to improve code maintenance and I would like to hear your opinion on the question I asked.

Thanks, Ruben! This is a great improvement.

2024-03-07 20:00 UTC, leandrodamascena commented on aws_lambda_powertools/event_handler/middlewares/openapi_validation.py
> +        self._response_serializer = response_serializer
Is is possible to add docstring here @rubenfonseca?

2024-03-07 20:00 UTC, leandrodamascena commented on aws_lambda_powertools/event_handler/openapi/encoders.py
> +    custom_serializer: Optional[Callable[[Any], str]] = None,
Please add this new parameter in the docstring.

2024-03-07 20:00 UTC, leandrodamascena commented on aws_lambda_powertools/event_handler/openapi/encoders.py
> +        return custom_serializer(obj)
I'm wondering here whether a custom serializer should take precedence over any other encoder. This is an explicit desire of the customer who wants to use a custom serializer. In this implementation, we only use the custom serializer if not an instance of Pydantic, Dataclass, str, int, and others.

What do you think? Make sense?

2024-03-08 08:17 UTC, rubenfonseca commented on aws_lambda_powertools/event_handler/openapi/encoders.py
> +        return custom_serializer(obj)
@leandrodamascena please note that this is *not* the response serializer. That is still used if the customer provides one. This is the *validation* serializer. When an object comes out of a function, we need to prepare it for validation with Pydantic, and for that we need to transform it into something that is `jsonable`. Internal mechanisms should still take precendence, but here we just add the option to prepare an unknown object for validation.

2024-03-08 08:53 UTC, leandrodamascena commented on aws_lambda_powertools/event_handler/openapi/encoders.py
> +        return custom_serializer(obj)
Thanks for the clear explanation, Ruben! Make sense about internal mechanisms and its precedence.

2024-03-08 09:27 UTC, rubenfonseca commented on aws_lambda_powertools/event_handler/openapi/encoders.py
> +        return custom_serializer(obj)
Actually your question made me think, and I'm renaming the parameter from `response_serializer` to `validation_serializer`, so it's more clear that it's not about the response.

2024-03-08 09:31 UTC, leandrodamascena approved these changes
APPROVED!!

2024-03-08 09:37 UTC, merged