refactor(logger): bring your own formatter, remove keys at runtime, custom JSON encoder/decoder
awslabs/aws-lambda-powertools-python pull request #404
Opened 2021-04-19 12:52 UTC by heitorlessa

**Issue #, if available:** #381 #387 #215 #98

## Description of changes:

Major refactor of Logger to **a)** make it more flexible for those coming from other loggers, **b)** bring your own formatter for those with a common structure that differs from our opinionated one, **c)** UX enhancements to add or remove keys from the logger, **d)** address long standing tech debts on  `LambdaPowertoolsFormatter`.

### New convenience property to change logger handler, if necessary

```python
from aws_lambda_powertools import Logger

logger = Logger()

handler = logger.registered_handler  # takes into account parent or child loggers
```

### Bring your own formatter

```python
from aws_lambda_powertools import Logger
from aws_lambda_powertools.logging.formatter import BasePowertoolsFormatter

class CustomFormatter(BasePowertoolsFormatter):
    custom_format = {}

    def append_keys(self, **additional_keys):
        # used by inject_lambda_context decorator, Logger initialization, and structure_log
        self.custom_format.update(additional_keys)

    def remove_keys(self, keys: Iterable[str]):
        # used by Logger public method
        for key in keys:
            self.custom_format.pop(key, None)

    def format(self, record: logging.LogRecord) -> str:  # noqa: A003
        return json.dumps(
            {
                "message": super().format(record),
                "timestamp": self.formatTime(record),
                "my_default_key": "test",
                **self.custom_format,
            }
        )

custom_formatter = CustomFormatter()
logger = Logger(logger_formatter=custom_formatter)
```

### Updating formatter made easier

```python
from aws_lambda_powertools import Logger

logger = Logger()

logger.append_keys(request_id="id", order_id="id")
logger.info("with both request and order id keys")

logger.remove_keys(["request_id"])
logger.info("with request id key only")
```

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)
* [x] **New features**
  * [x] Bring your own formatter via `Logger(log_formatter=...)`
    * [x] Create ABC to support custom formatters to enforce `append_keys` and `remove_keys`
    * [x] Update Logger to use `append_keys` for Lambda decorator and `structure_log` calls
  * [x] Add support for `utc=True`
* [x] **Tech debt**
  * [x] Introduce `append_keys`, `remove_keys` over `structure_log(append=True)` to align with other runtimes
  * [x] Allow customers to set bare minimum (only message, and xray_trace_id)
    * [x] Allow to suppress sampling_rate
    * [x] Remove sampling_rate when not in use (set to None by default over 0.0)
  * [x] Allow custom JSON serializer/deserializer for those seeking faster performance
  * [x] Compact logging to save on ingestion & storage cost (`separators[]` to remove whitespace)
  * [x] [Internal] Refactor standalone methods into staticmethods
  * [x] Rename testing to powertools formatter given we have vastly deviated from the original implementation
    * [x] Create alias for JsonFormatter to prevent breaking existing customers
  * [x] Add convenience properties to access handler and formatter
  * [x] Support all standard log attrs (%()s) if given via kwargs
* [ ] Update docstring parameters in Logger
* [ ] Update docstring parameters in Formatter
* [ ] Docstring and deprecation warning for `structlog` ahead of 2.0

---

**Create separate PR for docs to include enhancements**:

* [ ] Document examples
  * [ ] Default JSON fn for unserializable (json.dumps(data, default=json_default))
  * [ ] Std log attrs %()s support
  * [ ] Bring your own formatter
  * [ ] Bare minimal attrs (level, message, service)
  * [ ] Update all docs with additional TZ in timestamp
  * [ ] Bringing `orjson` for those seeking to gain every possible microsecond

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-19 17:36 UTC, michaelbrewer commented
@heitorlessa nice, this would help alot when you have company mandated structured logging formats.

2021-04-21 04:28 UTC, heitorlessa commented
@bml1g12 - what are your thoughts on the UTC UX for your use case?

Anything else you need while I'm at it?

2021-04-21 06:06 UTC, bml1g12 commented
Currently, I am declaring in each handler 
```
LOGGER = Logger(datefmt="%Y-%m-%dT%H:%M:%SZ")
LOGGER._logger.handlers[0].formatter.converter = time.gmtime  #pylint: disable = protected-access
```
So in this new UX I would instead simply do
```
LOGGER = Logger(datefmt="%Y-%m-%dT%H:%M:%SZ", utc=True)
```
In each handler and the child would inherit this right?

If so, looks great to me! Much appreciated addition.

2021-04-21 07:33 UTC, heitorlessa commented
Yes exactly. I noticed you’re using RFC 8601 in your datefmt, I’ll make
sure this will be the default timestamp in v2, as changing now would break
customers.

On Wed, 21 Apr 2021 at 08:06, Benjamin Lowe ***@***.***>
wrote:

> Currently, I am declaring in each handler
>
> LOGGER = Logger(datefmt="%Y-%m-%dT%H:%M:%SZ")
> LOGGER._logger.handlers[0].formatter.converter = time.gmtime  #pylint: disable = protected-access
>
> So in this new UX I would instead simply do
>
> LOGGER = Logger(datefmt="%Y-%m-%dT%H:%M:%SZ", utc=True)
>
> In each handler and the child would inherit this right?
>
> If so, looks great to me! Much appreciated addition.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/404#issuecomment-823802137>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBA6QLUPK7IESZ3EUXTTJZTORANCNFSM43FYVHHQ>
> .
>

2021-04-21 12:30 UTC, bml1g12 commented
Yeah I chose this as I saw a few blogs recommending it as a standard across languages for structured logging; I think its the default for javascript logging library maybe

2021-04-22 00:02 UTC, michaelbrewer commented
@heitorlessa I am liking these changes so long, I am glad to see that now even `sampling_rate` can be suppressed :)

2021-04-22 00:13 UTC, michaelbrewer commented on aws_lambda_powertools/logging/formatter.py
> +        return ts_formatted
```suggestion
        record_ts = self.converter(record.created)
        if datefmt:
            return time.strftime(datefmt, record_ts)

        # NOTE: Python `time.strftime` doesn't provide msec directives
        # so we create a custom one (%F) and replace logging record ts
        # Reason 2 is that std logging doesn't support msec after TZ
        msecs = "%03d" % record.msecs
        custom_fmt = self.default_time_format.replace(self.custom_ms_time_directive, msecs)
        return time.strftime(custom_fmt, record_ts)
```

2021-04-22 00:14 UTC, michaelbrewer requested changes
LGTM, just a minor tweak and typo

2021-04-22 13:30 UTC, merged