fix(logger): correctly pick powertools or custom handler in custom environments
awslabs/aws-lambda-powertools-python pull request #4295
Opened 2024-05-08 10:55 UTC by heitorlessa

**Issue number:** #4277

## Summary

This PR fixes a bug when a compute environment or customer preconfigures a standard logging logger with the same Powertools logger name.

Previously, we'd always pick the first handler - child or parent. However, it led to pick the incorrect one if a logger we're creating for the first time (`Logger`) was already pre-setup through other means (`logging.getLogger`).

```python
import logging
import os

from aws_lambda_powertools import Logger

service_name = os.getenv("POWERTOOLS_SERVICE_NAME")

# A environment, third-party library, or customer intentionally creates a logger with the same name as Powertools
# and add a Handler

logging.getLogger(service_name).addHandler(logging.StreamHandler())

logger = Logger(service=service_name)  # Powertools will ask standard logging to give the previously setup logger, then configure another handler etc as expected 
```

### Changes

> Please provide a summary of what's being changed

- [x] Encapsulate handler selection in `_get_handler` 
- [x] Reverse depend `registered_handler` on `_get_handler`
- [x] Logger with two handlers and log items use both of them
- [x] The above with a child logger
- [x] Add explicit test for orphaned child without handler that will fail with `AttributeError`
- [ ] Create a backwards compatible exception to provide actionable error on orphaned child formatter (e.g., child init before parent and append_keys)

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-05-08 15:22 UTC, heitorlessa commented
Docs cleaned up to make it clearer the side effects of child loggers; removed a ton of banners we accrued over the years.

<img width="1324" alt="image" src="https://github.com/aws-powertools/powertools-lambda-python/assets/3340292/e6fd1f13-cb9e-4144-ab5b-f826ac9a0142">

2024-05-13 11:21 UTC, leandrodamascena requested changes
Hey @heitorlessa! I've pushed a commit with two small things, but this LGTM! Congrats for this great catch and fix.

2024-05-13 11:21 UTC, leandrodamascena commented on .gitignore
> +bla.py
Need to remove this.

2024-05-13 11:21 UTC, leandrodamascena commented on .markdownlint.yaml
> +MD040: false
Linter won't comply if we remove spaces in the Diagram.

2024-05-13 11:23 UTC, leandrodamascena approved these changes, later dismissed

2024-05-13 13:46 UTC, heitorlessa commented on aws_lambda_powertools/logging/constants.py
> +LOGGER_ATTRIBUTE_PRECONFIGURED = "init"
```suggestion
# logger.init attribute is set when Logger has been configured 
LOGGER_ATTRIBUTE_PRECONFIGURED = "init"
```

2024-05-13 13:46 UTC, heitorlessa commented on aws_lambda_powertools/logging/constants.py
> +LOGGER_ATTRIBUTE_POWERTOOLS_HANDLER = "powertools_handler"
```suggestion
# logger.powertools_handler is set with Powertools Logger handler; useful when there are many handlers
LOGGER_ATTRIBUTE_POWERTOOLS_HANDLER = "powertools_handler"
```

2024-05-13 13:50 UTC, leandrodamascena approved these changes

2024-05-13 13:50 UTC, merged