feat: Add APIGateway*EventModelV2 to parser #434
awslabs/aws-lambda-powertools-python pull request #441
Opened 2021-05-24 06:12 UTC by risenberg-cyberark

Support for API GW v2 proxy schema & envelope.
see issue #434

2021-05-24 08:13 UTC, xpayn commented
Good job! :)

2021-05-28 10:09 UTC, heitorlessa requested changes
One tiny change that it seems to be a typo on a property that doesn't exist.

2021-05-28 10:09 UTC, heitorlessa commented on aws_lambda_powertools/utilities/parser/models/apigwv2.py
> +    property
This seems off - perhaps a typo?

```suggestion

```

2021-05-28 12:35 UTC, heitorlessa approved these changes

2021-05-28 12:39 UTC, heitorlessa commented
merging - thanks a lot @risenberg-cyberark ;)

2021-05-28 12:48 UTC, merged