feat(events): Update and Add Cognito User Pool Events
awslabs/aws-lambda-powertools-python pull request #4423
Opened 2024-05-29 06:45 UTC by knightmre

**Issue number:** [#3987](https://github.com/aws-powertools/powertools-lambda-python/issues/3987)

## Summary

### Changes

> Please provide a summary of what's being changed

This change updates the UserMigrationTriggerEvent data class, adds the V2 of [Pre Token Generation Lambda Triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html) and adds two new data classes for [Custom Sender Lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html)

### User experience

> Please share what the user experience looks like before and after this change

Events did not exist before. A workaround was to self-implement the data classes by inheriting base classes like so:

**Before**

```python
from typing import Optional

from aws_lambda_powertools.utilities.data_classes import cognito_user_pool_event
from aws_lambda_powertools.utilities.data_classes import common

class CustomSMSSenderTriggerEventRequest(common.DictWrapper):
    @property
    def code(self) -> str:
        """A string for you to use as the placeholder for the verification code in the custom message."""
        return self["request"]["code"]

    @property
    def user_attributes(self) -> dict[str, str]:
        """One or more name-value pairs representing user attributes. The attribute names are the keys."""
        return self["request"]["userAttributes"]

    @property
    def client_metadata(self) -> Optional[dict[str, str]]:
        """One or more key-value pairs that you can provide as custom input to the Lambda function
        that you specify for the pre sign-up trigger."""
        return self["request"].get("clientMetadata")

class CustomSMSSenderEvent(cognito_user_pool_event.BaseTriggerEvent):

    @property
    def request(self) -> CustomSMSSenderTriggerEventRequest:
        return CustomSMSSenderTriggerEventRequest(self._data)

```

```python

from . import CustomSMSSenderEvent

@data_classes.event_source(data_class=CustomSMSSenderEvent)
def handler(event: CustomSMSSenderEvent, context):
    return handle_event(event=event)
```

**After**

```python

from aws_lambda_powertools.utilities.data_classes.cognito_user_pool_event import CustomSMSSenderTriggerEvent

@data_classes.event_source(data_class=CustomSMSSenderTriggerEvent)
def handler(event: CustomSMSSenderTriggerEvent, context):
    return handle_event(event=event)
```

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-05-29 09:39 UTC, leandrodamascena commented
Hi @knightmre this is a super detailed PR with an impressive level of awesome docs/documentation. I'm working on other PRs and will schedule the first review of this PR for early next week.

Thanks

2024-05-29 10:00 UTC, knightmre commented
> Hi @knightmre this is a super detailed PR with an impressive level of awesome docs/documentation. I'm working on other PRs and will schedule the first review of this PR for early next week.
> 
> Thanks

Hi, thanks for your time, I just found out I missed out on some tests so I'll be reworking this a little before your review.

2024-06-11 10:20 UTC, leandrodamascena commented
Reviewing this now.

2024-06-11 13:32 UTC, leandrodamascena requested changes
Hey @knightmre! Well done! This was one of the most detailed PRs I've looked at. Creating all those events in Cognito must have taken a lot of hard work and I'm sure you spent some days. I tried making some myself, and it took me over a day. 

I just made a few small comments to your great work. 🚀

2024-06-11 13:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
> +        return self.get("claimsToAddOrOverride")
```suggestion
    def claims_to_add_or_override(self) -> Dict[str, str]:
        return self.get("claimsToAddOrOverride") or {}
```

2024-06-11 13:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
> +        return self.get("claimsToSuppress")
```suggestion
    def claims_to_suppress(self) -> List[str]:
        return self.get("claimsToSuppress") or []
```

2024-06-11 13:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
> +        return self.get("scopesToAdd")
```suggestion
    def scopes_to_add(self) -> List[str]:
        return self.get("scopesToAdd") or []
```

2024-06-11 13:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
> +        return self.get("scopesToSuppress")
```suggestion
    def scopes_to_suppress(self) -> List[str]:
        return self.get("scopesToSuppress") or []
```

2024-06-11 13:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
> +        return self["request"].get("clientMetadata")
```suggestion
    def client_metadata(self) -> Dict[str, str]:
        """One or more key-value pairs that you can provide as custom input to the
        custom email sender Lambda function trigger. To pass this data to your Lambda function,
        you can use the ClientMetadata parameter in the AdminRespondToAuthChallenge and
        RespondToAuthChallenge API actions. Amazon Cognito doesn't include data from the
        ClientMetadata parameter in AdminInitiateAuth and InitiateAuth API operations
        in the request that it passes to the post authentication function.
        """
        return self["request"].get("clientMetadata") or {}
```

2024-06-11 13:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/cognito_user_pool_event.py
> +        return self["request"].get("clientMetadata")
```suggestion
    def client_metadata(self) -> Dict[str, str]:
        """One or more key-value pairs that you can provide as custom input to the
        custom SMS sender Lambda function trigger. To pass this data to your Lambda function,
        you can use the ClientMetadata parameter in the AdminRespondToAuthChallenge and
        RespondToAuthChallenge API actions. Amazon Cognito doesn't include data from the
        ClientMetadata parameter in AdminInitiateAuth and InitiateAuth API operations
        in the request that it passes to the post authentication function.
        """
        return self["request"].get("clientMetadata") or {}
```

2024-06-12 03:09 UTC, knightmre commented
> Hey @knightmre! Well done! This was one of the most detailed PRs I've looked at. Creating all those events in Cognito must have taken a lot of hard work and I'm sure you spent some days. I tried making some myself, and it took me over a day.
> 
> I just made a few small comments to your great work. 🚀

Hi @leandrodamascena Thanks for the review. I've included your comments and updated the PR.

2024-06-12 09:53 UTC, leandrodamascena approved these changes
I'm going to say this again: amazing work @knightmre!

APPROVED!

2024-06-12 10:09 UTC, sthulb approved these changes

2024-06-12 10:11 UTC, merged