feat(event_handler): add OpenAPI extensions feature - WIP
awslabs/aws-lambda-powertools-python pull request #4703
Opened 2024-07-08 00:28 UTC by leandrodamascena

**Issue number:** #4035 

## Summary

### Changes

Work in progress - I'll update PR Body and what's missing soon.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-07-08 19:16 UTC, leandrodamascena commented
Things missing in this PR:

- [ ] Schedule a meeting with @sthulb to see if we can take advantage of Pydantic models when serializing OpenAPI extensions
- [ ] Update the documentation
- [ ] Create a e2e tests
- [ ] Review the code to see if we can improve

2024-07-09 18:47 UTC, leandrodamascena commented
> Things missing in this PR:
> 
> * [x]  Schedule a meeting with @sthulb to see if we can take advantage of Pydantic models when serializing OpenAPI extensions
> * [x]  Update the documentation
> * [x]  Create a e2e tests
> * [x]  Review the code to see if we can improve

We had a meeting this morning and agreed with the current implementation.

2024-07-09 18:48 UTC, leandrodamascena commented
Hey @heitorlessa and @sthulb this PR is ready to review.

2024-07-10 09:51 UTC, sthulb requested changes
I think there needs to be more tests overall. This seems like an area unit tests should be added – this would be an ideal bit of functionality to add some

2024-07-10 11:03 UTC, leandrodamascena commented
Just a quick note about codecov: This is not possible to fix the codecov errors. Our workflow just submit codecov report when testing with Pydantic v1.. We don't submit reports with Pydantic v2, so, there is no way to fix that now :disappointed:

![image](https://github.com/aws-powertools/powertools-lambda-python/assets/4295173/6f461781-0eb5-48a2-b1a1-768dc43cd138)

2024-07-10 12:28 UTC, sthulb commented on aws_lambda_powertools/event_handler/openapi/models.py
> +class OpenapiExtensions(BaseModel):
This class should be called: `OpenAPIExtensions`

2024-07-10 12:43 UTC, leandrodamascena commented on aws_lambda_powertools/event_handler/openapi/models.py
> +class OpenapiExtensions(BaseModel):
Make sense! Changing...

2024-07-10 16:06 UTC, leandrodamascena commented
Hey @sthulb, can you please review again?

2024-07-11 10:45 UTC, sthulb approved these changes

2024-07-15 10:13 UTC, merged