feat: validate() returns output from fastjsonschema.validate()
awslabs/aws-lambda-powertools-python pull request #4839
Opened 2024-07-29 14:53 UTC by dracozombie19

**Issue number: 4797**

## Summary

### Changes

The Validation feature has been updated to return the output of the `fastjsonschema.validate()` function.  When validating the payload, `fastjsonschema` returns the payload with `default` values populated where applicable.

### User experience

Consider this line of code:

```python
from aws_lambda_powertools.utilities.validation import validate

val_payload = validate(payload, schema)
```

Before the change, `val_payload` would be `None`.  After the change, it would be the original `payload` value, with any `default` values inserted for fields that were not provided.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ x ] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [ x ] I have performed a self-review of this change
* [ x ] Changes have been tested
* [ x ] Changes are documented
* [ x ] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change? - No</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-08-02 17:13 UTC, leandrodamascena requested changes
Hey @dracozombie19! Thanks a lot for investing time in this PR, returning the validate schema and including the payload is really helpful! Overall this look great, just a small thing about Sonarcloud but it's easy to fix.

One thing that is missing here is to update our documentation with this new behavior because we're now returning the JSON. I'll add an example in our documentation and I expect to merge this PR on Monday.

Great work! 🚀

2024-08-02 17:13 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/validation/base.py
> +        in the response.
Nice one! We love docstring ❤️

2024-08-02 17:13 UTC, leandrodamascena commented on tests/functional/validator/conftest.py
> +        "$id": "http://example.com/example.json",
Sonarcloud is [complaining](https://sonarcloud.io/project/security_hotspots?id=aws-powertools_powertools-lambda-python&pullRequest=4839&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true) about security here. Can you please make this endpoint https?

 ```suggestion
        "$schema": "https://json-schema.org/draft-07/schema",
        "$id": "https://example.com/example.json",
```

2024-08-05 17:43 UTC, leandrodamascena commented
Hey @sthulb I made some changes in this PR and I need your review here, pls.

2024-08-06 09:28 UTC, sthulb approved these changes

2024-08-06 09:41 UTC, leandrodamascena approved these changes

2024-08-06 09:42 UTC, merged