fix(utilities): DDB Large numbers
awslabs/aws-lambda-powertools-python pull request #4863
Opened 2024-07-31 20:40 UTC by sthulb

**Issue number:** #4845 

## Summary

### Changes

> Please provide a summary of what's being changed

Checks for the presence of large numbers in DDB records and then truncates them if they end in 0, as per the DDB docs behaviour:
> In DynamoDB, numbers are represented as variable length. Leading and trailing zeroes are trimmed.

### User experience

> Please share what the user experience looks like before and after this change

Before: 
based on the `decimal.Context`, any number larger than 38 chars would throw an uncaught exception.

After: 
Trailing 0s are trimmed.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [X] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [X] I have performed a self-review of this change
* [X] Changes have been tested
* [X] Changes are documented
* [X] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-07-31 22:32 UTC, leandrodamascena requested changes
Hi @sthulb! Thanks for working on this PR!

We have a few things to fix before we can merge this.

2024-07-31 22:32 UTC, leandrodamascena commented on aws_lambda_powertools/utilities/data_classes/dynamo_db_stream_event.py
> +            value = value[:-tail]
If value is something like `00000000001234567891234567891234567834343978` this code will fail. Value is greater than 38, but there is no trailing zeros, what will result in the invalid expression `value = value[-0]`.

If I'm not wrong, Decimal always remove leading zeros, what means that we can use `lstrip` to remove leading zeros. Make sense?

2024-07-31 22:32 UTC, leandrodamascena commented on tests/unit/data_classes/required_dependencies/test_dynamo_db_stream_event.py
> +def test_dynamodb_stream_record_deserialization_large_int():
Nice test!! We need to create another one with leading zeros.

2024-08-02 10:12 UTC, leandrodamascena approved these changes

2024-08-02 10:16 UTC, dreamorosi approved these changes

2024-08-02 10:17 UTC, merged