test: cors is opt out if enabled
awslabs/aws-lambda-powertools-python pull request #4882
Opened 2024-08-03 20:13 UTC by Wurstnase

**Issue number: #4881**

## Summary

### Changes

opt-out cors instead of opt-in.

### User experience

when a resolver has cors enabled, routes can opt out only

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-08-04 21:15 UTC, leandrodamascena requested changes
Thanks for sending this PR @Wurstnase, great catch!!! I just left a quick comment before we merge.

Thanks

2024-08-04 21:15 UTC, leandrodamascena commented on tests/functional/event_handler/required_dependencies/test_api_gateway.py
>      def with_cors() -> Response:
I'm wondering if we can remove `cors=True` here. It's the default behavior when cors is set in `ApiGatewayResolver`. What do you think?

2024-08-05 06:17 UTC, tonnico commented on tests/functional/event_handler/required_dependencies/test_api_gateway.py
>      def with_cors() -> Response:
Good point. I will check and test some other places to.

2024-08-05 19:33 UTC, Wurstnase commented on tests/functional/event_handler/required_dependencies/test_api_gateway.py
low hanging fruit to test the UserWarnings and reduce noise in the pytest output

2024-08-05 21:59 UTC, leandrodamascena commented on tests/functional/event_handler/required_dependencies/test_api_gateway.py
Great attention to details @Wurstnase! Thank you so much!! ❤️

2024-08-05 22:00 UTC, leandrodamascena approved these changes
APPROVED! 🚀 

Thanks @Wurstnase

2024-08-05 22:06 UTC, merged