fix(openapi): Allow values of any type in the examples of the Parameter Object.
awslabs/aws-lambda-powertools-python pull request #5575
Opened 2024-11-17 06:02 UTC by tonsho

**Issue number:** #5573

## Summary

### Changes

Allow values of any type in the examples of the Parameter Object.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-11-17 21:18 UTC, leandrodamascena requested changes
Hi @tonsho! Thank you so much for this PR, you were super quick!

I just left a quick comment before we merge this.

2024-11-17 21:18 UTC, leandrodamascena commented on tests/functional/event_handler/_pydantic/test_openapi_params.py
> +            Query(gt=0, lt=100, examples=[10]),
I would prefer not to change this test, but rather add a new one with the new accepted types like int, boolean, float and others.

2024-11-18 14:19 UTC, tonsho commented on tests/functional/event_handler/_pydantic/test_openapi_params.py
> +    assert example.value == 10
**Temporarily avoid test failures.**

The `examples` should be under `parameters`, not under `schema`.
https://swagger.io/specification/#parameter-object

I was not able to change the output location of the `examples`. In this PR, it will only enable the definition of `examples` in the Schema Object.
https://swagger.io/specification/#schema-object

# wrong

```json
        "parameters": [
          {
            "required": false,
            "schema": {
              "type": "integer",
              "exclusiveMaximum": 100.0,
              "exclusiveMinimum": 0.0,
              "title": "Count",
              "default": 1,
              "examples": [
                {
                  "summary": "Example 1",
                  "description": null,
                  "value": 10,
                  "externalValue": null
                }
              ]
            },
            "name": "count",
            "in": "query"
          }
        ],
```
<img width="383" alt="image" src="https://github.com/user-attachments/assets/b1b2d430-f7f2-4d39-8196-5a8f0c372914">

# expected

```json
        "parameters": [
          {
            "required": false,
            "schema": {
              "type": "integer",
              "exclusiveMaximum": 100.0,
              "exclusiveMinimum": 0.0,
              "title": "Count",
              "default": 1
            },
            "examples": [
              {
                "summary": "Example 1",
                "description": null,
                "value": 10,
                "externalValue": null
              }
            ],
            "name": "count",
            "in": "query"
          }
        ],
```
<img width="401" alt="image" src="https://github.com/user-attachments/assets/ace57d4c-d40c-4fbb-83f4-fed3a4adbec9">

2024-11-18 17:57 UTC, leandrodamascena commented on tests/functional/event_handler/_pydantic/test_openapi_params.py
> +    assert example.value == 10
Hi @tonsho! Thanks for reporting this error! I'll create a new issue to resolve this.

2024-11-19 10:21 UTC, leandrodamascena commented on tests/functional/event_handler/_pydantic/test_openapi_params.py
> +    assert example.value == 10
New issue: https://github.com/aws-powertools/powertools-lambda-python/issues/5587

I'm approving and merging this PR.

2024-11-19 10:35 UTC, leandrodamascena approved these changes
Thanks for working on this and reporting a new error @tonsho!

APPROVED!

2024-11-19 10:36 UTC, sthulb approved these changes

2024-11-19 10:37 UTC, merged