docs: Document auto transform feature in parameters get_multiple()
awslabs/aws-lambda-powertools-python pull request #573
Opened 2021-07-29 12:32 UTC by dreamorosi

**Issue #, if available:**
#562 

## Description of changes:

Added subsection under "Utilities > Parameters > Advanced > Deserializing values with transform parameter" titled "Infer transform from parameter suffix with `get_multiple()`" to document auto transform behaviour.

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-29 16:22 UTC, michaelbrewer commented on docs/utilities/parameters.md
> +
Probably should terminate the python code example with 

```suggestion
````
```

2021-07-29 16:23 UTC, michaelbrewer commented on docs/utilities/parameters.md
> +````
and then remove this one?

2021-07-29 16:23 UTC, michaelbrewer requested changes
Looking good, just some formatting issue

2021-07-30 14:28 UTC, dreamorosi commented
Fixed both formatting issues, thanks for the review

2021-08-04 00:12 UTC, michaelbrewer commented
@heitorlessa - don't forget to have a look at this one :)

2021-08-04 18:00 UTC, heitorlessa commented
yep I have not. I need to revisit the wording on that sub-section. I think we can improve there, but I need to finish the Feature Flags first as that's the biggest piece of work right now

2021-08-10 19:11 UTC, heitorlessa approved these changes

2021-08-10 19:11 UTC, heitorlessa commented
Thanks a lot everyone - made minor changes to make it easier to find in the docs. Merging!

2021-08-10 19:16 UTC, merged