feat (feature flags): Add not_in action and rename contains to in
awslabs/aws-lambda-powertools-python pull request #589
Opened 2021-08-05 07:36 UTC by risenberg-cyberark

Add IN action instead of contains
Add NOT_IN action

2021-08-05 07:38 UTC, risenberg-cyberark commented
@heitorlessa  there ya go

2021-08-05 07:43 UTC, heitorlessa requested changes

2021-08-05 07:43 UTC, heitorlessa commented on aws_lambda_powertools/utilities/feature_flags/feature_flags.py
> +            condition_value = condition.get(schema.CONDITION_VALUE)
```suggestion
            cond_action = condition.get(schema.CONDITION_ACTION, "")
            cond_value = condition.get(schema.CONDITION_VALUE)
```

2021-08-05 07:43 UTC, heitorlessa commented on aws_lambda_powertools/utilities/feature_flags/schema.py
> +    The value MUST be either EQUALS, STARTSWITH, ENDSWITH, IN
and NOT_IN?

2021-08-05 07:45 UTC, risenberg-cyberark commented on aws_lambda_powertools/utilities/feature_flags/schema.py
> +    The value MUST be either EQUALS, STARTSWITH, ENDSWITH, IN
will fix

2021-08-10 07:41 UTC, heitorlessa approved these changes

2021-08-10 07:41 UTC, merged