fix(warning): fix python3.10 distutils deprecation
awslabs/aws-lambda-powertools-python pull request #921
Opened 2021-12-21 06:21 UTC by nayaverdier

**Issue #, if available:** Fixes #906

## Description of changes:

Removes dependency on distutils.

**Checklist**

 

* [ ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-21 07:09 UTC, heitorlessa requested changes
Tiny change and we're good to go ;-)

2021-12-21 07:09 UTC, heitorlessa commented on aws_lambda_powertools/shared/functions.py
> +def _strtobool(value):
As we're removing distutil package and this will be deprecated, it's okay to keep the same name (no `_`)

2021-12-21 14:27 UTC, heitorlessa approved these changes

2021-12-21 14:28 UTC, heitorlessa commented
Thanks a lot for the future-proof change @nayaverdier  :) much appreciated!

2021-12-21 14:28 UTC, merged

2021-12-21 14:55 UTC, jplock commented on aws_lambda_powertools/shared/functions.py
> +def strtobool(value):
does this need typing hints?

2021-12-22 06:22 UTC, michaelbrewer commented on aws_lambda_powertools/shared/functions.py
> +def strtobool(value):
probably a good idea :)

2021-12-22 06:24 UTC, heitorlessa commented
Don’t worry, we’re gonna tackle this and 36 others during mypy fixes

On Wed, 22 Dec 2021 at 07:22, Michael Brewer ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In aws_lambda_powertools/shared/functions.py
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/921#discussion_r773627347>
> :
>
> >  from typing import Any, Optional, Union
>
>
> +def strtobool(value):
>
> probably a good idea :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/921#discussion_r773627347>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBGA7QTYJQZK622G7J3USFVBFANCNFSM5KPL25IQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***
> .com>
>

2021-12-22 06:25 UTC, michaelbrewer commented
haha. mypy does not complain about untyped methods :)

2021-12-22 11:57 UTC, heitorlessa commented
IIRC there’s a strict mode that it can flag

On Wed, 22 Dec 2021 at 07:25, Michael Brewer ***@***.***>
wrote:

> haha. mypy does not complain about untyped methods :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/awslabs/aws-lambda-powertools-python/pull/921#issuecomment-999319189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZPQBCQO4NKPA52RYCY52TUSFVOVANCNFSM5KPL25IQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>