chore(data-classes): fix some small typos in doc strings and clean up
awslabs/aws-lambda-powertools-python pull request #937
Opened 2022-01-04 22:44 UTC by michaelbrewer

**Issue #, if available:**

## Description of changes:

Changes:
- Use correct wording: `built-in`, `its`, `sign in`, `all the` and `case-sensitive`
- Modern use of `super()`
- Use `startswith` instead of `resource[:1] == "/"`

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-06 12:39 UTC, michaelbrewer commented
@heitorlessa  - some small housekeeping fixes.

2022-01-11 14:22 UTC, heitorlessa requested changes
one question on whether you meant `startswith` vs `==`, as I can't remember what the possible values can be.

2022-01-11 15:54 UTC, michaelbrewer commented on aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
> +        if resource.startswith("/"):
for readability. Later this can be replaced with `removeprefix`

2022-01-11 16:43 UTC, heitorlessa requested changes
Thanks for the changes - one last one, please remove the empty `logfile`, as it seems to have been added by accident.

2022-01-11 16:44 UTC, heitorlessa commented on aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
> +        if resource.startswith("/"):
If you can add an one-line comment on that resource line it'd be great to help onboard new people to it.

2022-01-11 18:29 UTC, michaelbrewer commented on aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
> +        if resource.startswith("/"):
@heitorlessa tried anoher one

2022-01-11 20:02 UTC, michaelbrewer commented on aws_lambda_powertools/utilities/data_classes/api_gateway_authorizer_event.py
> +        if resource.startswith("/"):
@heitorlessa - it is using `lstrip` now which is simple and fast

2022-01-12 08:30 UTC, heitorlessa approved these changes

2022-01-12 08:32 UTC, heitorlessa commented
Updated description on `.lstrip` to clarify what this is for for anyone looking at this in the future.

2022-01-12 08:32 UTC, merged