docs: improve "testing your code" section for graphql event handler
awslabs/aws-lambda-powertools-python pull request #996
Opened 2022-02-03 15:49 UTC by cakepietoast

**Issue #, if available:** #857

## Description of changes:

Small improvements to "Testing Your Code" section in of graphql event handlers doc. Made example more relevant to a real application rather than borrowing our own example test, and added an example for async tests.

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-03 16:07 UTC, heitorlessa commented on docs/core/event_handler/appsync.md
> +      mock_event = json.load(fh)
Can we use Pathlib and a context manager to make it safer? 

```suggestion
      json_file = Path("appSyncDirectResolver.json")
      with json_file.open() as f:
          mock_event = json.load(fh)
```

2022-02-03 16:08 UTC, heitorlessa commented on docs/core/event_handler/appsync.md
> +      mock_event = json.load(fh)
same here - we'd want to give them a sound advice

2022-02-03 16:09 UTC, heitorlessa requested changes
Looks much better. Only change is to make sure we handle a file descriptor correctly in the sample test

2022-02-04 13:13 UTC, cakepietoast commented
Suggested change added!

2022-02-04 15:03 UTC, heitorlessa approved these changes

2022-02-04 15:03 UTC, merged